### ISSUE TITLE
Add delivered event

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#10]
`delivered` event is not added to aedes yet.

**Comment by mcollina** [comment]
Yes, it's missing. It should be easy to add though.

Just for a reference, here is where it is originally emitted in Mosca:
https://github.com/mcollina/mosca/blob/2694214e230a6b1febfd40fa55c7d33d40876fb0/lib/client.js#L383

**Comment by behrad** [comment]
yea, and that line was committed by me if you remember @mcollina :)) same for this topic ;)

I want to make sure the very first version of aedes is feasible for me to port my app on, this is my main concern :+1:

**Comment by guptaashishiitr** [comment]
@mcollina : Do you know when can we have delivered event?

**Comment by behrad** [comment]
I'll create a PR this week @guptaashishiitr

**Comment by pkinney** [comment]
Submitted a PR #39 that should address this.  Let me know if this is the desired behavior.  I tried to repeat what was done in Mosca referenced above.

**Comment by behrad** [comment]
Current `ack`event is passing the `puback` packet instead of the original packet delivered. Mosca is passing the original packet, so that application can use `topic/payload` to know which published message the ack is associated to. 

Another nice solution could be the `packet.messageId` however application is un-aware of that id in publish event listener, in the latter case Aedes should also pass broker's messageId back to the publish listener.

One of the above should be implemented @mcollina

**Comment by mcollina** [comment]
@behrad you are right. This change requires a change in the persistences modules, mainly the call to https://github.com/mcollina/aedes-persistence#instanceoutgoingclearmessageidclient-packet-callbackerr need to also return the packet.

Moreover, for QoS 2 we need to change https://github.com/mcollina/aedes-persistence#instanceoutgoingupdateclient-packet-callbackerr to retain the original packet (currently it is overwritten during the QoS 2 flow), or at least keep `topic` and `payload` around.

**Comment by mcollina** [comment]
Can you give some help in this one? It will probably require a bit of rework on the persistences.

**Comment by behrad** [comment]
Sure, I'll check this.

**Comment by behrad** [comment]
> Moreover, for QoS 2 we need to change https://github.com/mcollina/aedes-persistence#instanceoutgoingupdateclient-packet-callbackerr to retain the original packet (currently it is overwritten during the QoS 2 flow), or at least keep topic and payload around.

for QOS 2 shouldn't we ack on PUBCOMP instead?

**Comment by behrad** [comment]
I don't see how `emit('ack')` is called for QOS 2 now in aedes!? @mcollina

**Comment by behrad** [comment]
Please first merge https://github.com/mcollina/aedes-persistence/pull/2
After updating aedes-persistence inside, #54 will pass :)

**Comment by mcollina** [comment]
@behrad 

> I don't see how `emit('ack')` is called for QOS 2 now in aedes!? 

Both pubcomp and puback are handled in the same way.
https://github.com/mcollina/aedes/blob/fd95dfc065243d150285f477b6adcd0aff10dbb1/lib/handlers/index.js#L35-L38

**Comment by behrad** [comment]
Ok great, I was looking for a pubcomp.js file in handlers ;)

**Comment by behrad** [comment]
I also filed https://github.com/mcollina/aedes-persistence-redis/pull/5, do you think these 3 PRs can now be merged  @mcollina ?

**Comment by mcollina** [comment]
Releasing now (aedes is 0.19.0).
