### ISSUE TITLE
mosca or aedes, which one is better?

### ISSUE THREAD

**Issue by arden** [mcollina/aedes#101]
mosca or aedes, which one is better in production?

**Comment by mcollina** [comment]
Mosca is more battle tested and more stable. Aedes is more lightweight, fast, but as you have seen it requires more hardening against edge cases.

**Comment by jyotman** [comment]
@mcollina is Mosca gonna be merged/based on Aedes eventually?

**Comment by mcollina** [comment]
Big question. In theory yes, but it might also stay two separate things.
Il giorno ven 5 mag 2017 alle 19:56 Jyotman Singh <notifications@github.com>
ha scritto:
