### ISSUE TITLE
how to create a wss ?

### ISSUE THREAD

**Issue by xiclopex** [mcollina/aedes#107]
Hi folks, Aedes is amazing.
I have a question. how to create a wss connection? 
I can create a standard ws, and tcp TLS, but I don´t know how to create a wss.

**Comment by cordovapolymer** [comment]
@xiclopex ,

its the same as ws, just require https module instead of http and specify your certificates in options.

**Comment by cordovapolymer** [comment]
https://nodejs.org/api/https.html#https_https_createserver_options_requestlistener

**Comment by mcollina** [comment]
Closing, as it should be solved.
