### ISSUE TITLE
retain flag is always true

### ISSUE THREAD

**Issue by kailunc** [mcollina/aedes#110]
I am trying to differentiate between "live" packets and "stored" packets it receives by using the packet.retain flag but it seems that the retain flag is set to true in both scenarios.

retained message:
`
Packet {
  cmd: 'publish',
  retain: true,
  qos: 0,
  dup: false,
  length: 93,
  topic: 'some topic',
  payload: <some buffer> }
`

newly published message:
`
Packet {
  cmd: 'publish',
  retain: true,
  qos: 2,
  dup: false,
  length: 144,
  topic: 'some topic',
  payload: <some buffer>,
  messageId: 38600 }
`

I found a resolved issue in mosca (https://github.com/mcollina/mosca/issues/612) that are related, Does the following behavior apply for aedes? 
`
The retain flag is only set in a packet sent from broker to client in one case: the client subscribes and the broker sends out previously retained packets
`

**Comment by mcollina** [comment]
Very likely this has the same bug that was in Mosca. Would you like to send a PR?

**Comment by GavinDmello** [comment]
@mcollina  We're sending the same stored packet to emitPacket. So live packets will be retain true as well.

**Comment by mcollina** [comment]
> @mcollina We're sending the same stored packet to emitPacket. So live packets will be retain true as well.

Yeah 👍 , we need to fix this.

**Comment by mcollina** [comment]
This is fixed in #130 and v0.30.0
