### ISSUE TITLE
persistent clients not working correctly

### ISSUE THREAD

**Issue by bgau** [mcollina/aedes#111]
It seems that Aedes doesn't support persistent clients correctly. I am not deep enough into its code yet to propose a fix so I'd appreciate comments and suggestions or, indeed, a fix. 

The problem is that a persistent client is not supplied with subscribed QoS 1 or 2 messages which were published during the client's absence. 

Here's the sequence:

(1) client A connects with cleanSession=false, id="a"
(2) client A subscribes to topic T with QoS=1, granted.
(3) client A disappears (disconnects or crashes)
(4) client B connects (id != "a"), publishes message M to topic T, QoS=1, retain=false, then disconnects
(5) client A connects with cleanSession=false, id="a"

At step (5), we expect client A to receive message M published in step 4. 
This expectation seems clear to me from the MQTT protocol specification, and a cross-check with Mosquitto confirms this expected behavior. 

When A re-connects in step 5, it receives all new messages published on T, but it does not receive subscribed messages posted in its absence. Note this does not require A to re-subscribe.

**Comment by mcollina** [comment]
There are plenty of unit tests to cover those cases, so maybe there is something else going on. Which client are you using to do this? What is the configuration of your aedes?

**Comment by bgau** [comment]
Thanks for feedback. My Aedes instance uses default constructor except for persistence: AedesPersistenceLevel. The exact same test script succeeds with Mosquitto but fails with Aedes, using npmjs.com/package/mqtt for the clients. Which configuration aspect do you have in mind?

**Comment by mcollina** [comment]
@bgau can you please verify _without_ the level persistence?

**Comment by bgau** [comment]
Good point. I can confirm that Aedes() without persistence support behaves correctly, and catch-up does occur when client A re-connects.

**Comment by mcollina** [comment]
@bgau can you please verify if https://github.com/mcollina/aedes-persistence-level/pull/7 solves your problems?

**Comment by bgau** [comment]
I can confirm the fix with thanks.

**Comment by mcollina** [comment]
released aedes-persistence-level as v3.0.0
