### ISSUE TITLE
the client haven't    client#unsubscribe(subscriptions, [callback])  ?

### ISSUE THREAD

**Issue by arden** [mcollina/aedes#114]
the client have a client#subscribe(subscriptions, [callback]) 
and haven't  any client#unsubscribe(subscriptions, [callback])  ?

**Comment by mcollina** [comment]
Yes, I forgot :). Would you like to send a PR to add that?

**Comment by GavinDmello** [comment]
@arden  I think this can be closed
Check the latest release
