### ISSUE TITLE
Subscribe event called twice on restart

### ISSUE THREAD

**Issue by jyotman** [mcollina/aedes#117]
I'm using MQTT.js (from CLI) to connect to a minimal aedes broker running locally. When I subscribe to the broker for the first time then the *subscribe* event on the broker is called just once as expected after the *connect* event. But if I restart the aedes broker while the client is still connected and subscribed then the *subscribe* event is called twice after a single *connect* event.

Example with logs - 

Broker - 
```js
'use strict';

const Aedes = require('aedes'),
    port = 1883,
    redisMq = require('mqemitter-redis');

const mq = redisMq({
    host: 'localhost'
});

const aedes = Aedes({ mq: mq });
const server = require('net').createServer(aedes.handle);

server.listen(port, function() {
    console.log('Aedes server listening on port', port)
});

aedes.on('client', function(client) {
    console.log('new client', client.id)
});

aedes.on('subscribe', function(subscriptions, client) {
    console.log('subscription', client.id, subscriptions);
});
```

After activating the broker, connect the client like this - 
```bash
mqtt sub -t 'test/1' -h 'localhost' -i test_client
```

Produces the following log on aedes broker - 
```bash
new client test_client
subscription test_client [ { topic: 'test/1', qos: 0 } ]
```

Now if I clear the logs and restart the aedes broker, the following is logged immediately - 
```bash
new client test_client
subscription test_client [ { topic: 'test/1', qos: 0 } ]
subscription test_client [ { topic: 'test/1', qos: 0 } ]
```

As it can be seen, the *subscribe* event is logged twice on restarting the broker.

**Comment by mcollina** [comment]
which version of MQTT.js are you using? There was a bug there that might be causing this.

**Comment by jyotman** [comment]
2.8.0

**Comment by mcollina** [comment]
Does the same thing happens without redis?

**Comment by jyotman** [comment]
Yes, happening without redis too.

**Comment by mcollina** [comment]
It's a bug in MQTT.js.

@behrad do you have any clue?

**Comment by GavinDmello** [comment]
@mcollina It's the store calling it once and the client function itself calling subscribe. 
Just checked I get two subscribe packets on the connection.

**Comment by mcollina** [comment]
@GavinDmello can you assemble a PR?

**Comment by GavinDmello** [comment]
@mcollina I think it's happening only with the CLI .   How was it solved with simple MQTT.js , Is there some PR I can refer to ?

**Comment by mcollina** [comment]
@GavinDmello https://github.com/mqttjs/MQTT.js/pull/624 and https://github.com/mqttjs/MQTT.js/pull/631

**Comment by GavinDmello** [comment]
@jyotman Check with the latest mqtt.js

**Comment by jyotman** [comment]
Yes, seems to be fixed. :+1:
