### ISSUE TITLE
new client receives retained messages on not subscribed topics

### ISSUE THREAD

**Issue by bgau** [mcollina/aedes#119]
My broker is based on aedes with the level-db persistence module. The broker knows of two retained messages. New clients are sent the retained messages even though they never subscribed to the corresponding topic, as illustrated here:

`$ mosquitto_sub -v -t test/0/rq/# -i 300620171045

test/retained/api/0 test 0

test/retained/api/1 test 1
`

This appears to be in violation of the MQTT 3.1.1 protocol, section 3.3.1.3, RETAIN: _"...  it can be delivered to future subscribers whose subscriptions match its topic name ..."_ This client has no matching subscription.

**Comment by mcollina** [comment]
Can you please upload full steps to reproduce, including some example code for your broker?
Is it happening without the level-db persistence?

**Comment by bgau** [comment]
Steps to reproduce using the mosquitto console client tools:

(a) Publish a retained message:
mosquitto_pub -r -t test/retained/1 -m "test 1"

(b) Connect a new client (this uses cleanSession=true by default). Note that it does not subscribe to the retained topics:
mosquitto_sub -v -t /test/whatever 

In step (b), the client receives the retained messages when the level.db persistence driver is enabled. This is wrong. Without persistence but with the broker running throughout (a) and (b), the client does not receive the retained messages. This is correct.

**Comment by mcollina** [comment]
This is a bug in the level persistence, would you mind to attempt a fix?

**Comment by bgau** [comment]
Fair enough. I was hoping to get away without, of course, but I'll take a look.

**Comment by mcollina** [comment]
This is fixed on the latest level persistence.
