### ISSUE TITLE
broker keeps dying due to keep alive timeout

### ISSUE THREAD

**Issue by jeremytregunna** [mcollina/aedes#12]
I have aedes running as a broker locally, and whenever a keep alive timeout on the connect handler is missed, it fires an error, as I'd expect. However, that error kills the broker entirely, which is surprising me to me. Is this intended behaviour, and if so, why?

**Comment by mcollina** [comment]
I would say it is a bug, and it should be easy to fix.Would you like to
send a PR?

Il giorno mar 24 nov 2015 alle 22:15 Jeremy Tregunna <
notifications@github.com> ha scritto:

**Comment by jeremytregunna** [comment]
Actually, this issue is a bit misleading, it involves the packet timeout, and I'm not entirely sure if aedes is doing something buggy or if the keep alive timeout in a packet just doesn't make sense for a QoS0 packet. When I change my packet's keep alive to 0, the problem disappears, client has no connection issues even over long time ranges with inactivity. I'm thinking this might be something I'm doing wrong. Will report back in the next 24 hours with more information, or close this as user error. :)

**Comment by mcollina** [comment]
Aedes shuould not crash for a wrong packet. Can you please attach the
stacktrace?
Il giorno mar 24 nov 2015 alle 23:33 Jeremy Tregunna <
notifications@github.com> ha scritto:

**Comment by jeremytregunna** [comment]
Yeah it's below if it helps:

```
Error: keep alive timeout
    at keepaliveTimeout (/Users/jtregunna/Projects/hermes/node_modules/aedes/lib/handlers/connect.js:45:28)
    at timerWrapper [as _onTimeout] (/Users/jtregunna/Projects/hermes/node_modules/aedes/node_modules/retimer/retimer.js:21:16)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by jeremytregunna** [comment]
Also related:

```
client error null connect did not arrive in time
Error: connect did not arrive in time
    at null._onTimeout (/Users/jtregunna/Projects/hermes/node_modules/aedes/lib/client.js:87:24)
    at Timer.listOnTimeout (timers.js:92:15)
Error: connect did not arrive in time
    at null._onTimeout (/Users/jtregunna/Projects/hermes/node_modules/aedes/lib/client.js:87:24)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by mcollina** [comment]
Confirmed the first one (that lead to a crash).

Here is the client to reproduce:

```js
var mqtt = require('mqtt-packet')
var net = require('net')
var client = net.connect(1883)
var parser = mqtt.parser()

parser.on('packet', console.log)

client.on('data', parser.parse.bind(parser))

mqtt.writeToStream({
  cmd: 'connect',
  protocolId: 'MQTT',
  protocolVersion: 4,
  clean: true,
  keepalive: 1
}, client)

```

**Comment by mcollina** [comment]
Actually this is not a bug, it's me that left a `throw` in the example (https://github.com/mcollina/aedes/blob/master/example.js#L13).

This disappears removing that throw.

**Comment by tianyayouxiaer** [comment]
when I use pm2  to start up 4 aedes instanst,the aedes broker always print "client error SUB_1 keep alive timeout" (SUB_1 is my client.id),so I don,t know why it is !

**Comment by mcollina** [comment]
your client is not sending a keepalive message in time.
Il giorno sab 7 mag 2016 alle 17:51 tianyayouxiaer <notifications@github.com>
ha scritto:

**Comment by avinashsahoo** [comment]
> Also related:
> 
> ```
> client error null connect did not arrive in time
> Error: connect did not arrive in time
>     at null._onTimeout (/Users/jtregunna/Projects/hermes/node_modules/aedes/lib/client.js:87:24)
>     at Timer.listOnTimeout (timers.js:92:15)
> Error: connect did not arrive in time
>     at null._onTimeout (/Users/jtregunna/Projects/hermes/node_modules/aedes/lib/client.js:87:24)
>     at Timer.listOnTimeout (timers.js:92:15)
> ```

I'm facing this issue. How did you resolve this issue ?
