### ISSUE TITLE
Client Ip

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#128]
How can I access the client's IP address on the `client` object in aedes event hooks @mcollina ?

**Comment by mcollina** [comment]
you'll need to get it from client.stream I think. It would be nice to document it.

**Comment by behrad** [comment]
it was `client.connection.stream.remoteAddress` in mosca if I remember, however in aedes there's no `client.connection` and I couldn't find it out inside `client.stream` :(

**Comment by mcollina** [comment]
it's https://github.com/mcollina/aedes/blob/master/lib/client.js#L22.

We can rename that to `stream`, it might actually be better.

**Comment by behrad** [comment]
it is `client.conn.remoteAddress` 👍
