### ISSUE TITLE
restore series (instead of parallel) in SUBSCRIBE

### ISSUE THREAD

**Issue by mcollina** [mcollina/aedes#133]
After https://github.com/mcollina/aedes/pull/120, we can have an unordered granted array.
https://github.com/mcollina/aedes/blob/master/lib/handlers/subscribe.js#L63-L82 needs to be updated.

@behrad can you fire a PR for that?

**Comment by behrad** [comment]
> we can have an unordered granted array

Are you meaning that: Should the response granted array be ordered?
Why not to reorder them based on input subs array, when parallel is complete? instead of restoring to series?

**Comment by behrad** [comment]
Can you first add a failing test?
