### ISSUE TITLE
null client instance on some clientError events

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#138]
`CONNRESET` and `connect did not arrive in time` events both has NULL client parameter

**Comment by rahulbhanushali** [comment]
The places where error event is emitted passes **new Error()** object.
Changing it to literal objects will allow us to pass additional information along with error message.

@mcollina, do you think we can take this approach to emit error events ?

**Comment by mcollina** [comment]
Absolutely not. But we can create custom errors and attach properties to those errors.

**Comment by rahulbhanushali** [comment]
Alright.

Other approach would be to add required metadata to this error objects
instead of creating custom errors.

I don't see any additional benefits of custom errors since we are looking
to pass additional information and not do any customisations or call
functions.

**Comment by mcollina** [comment]
The only benefit is better typing for V8.

**Comment by GavinDmello** [comment]
@mcollina Here, I think client.id is null instead. We won't get the client Id till the connect arrives.

**Comment by behrad** [comment]
> We won't get the client Id till the connect arrives

Shouldn't we emit a generic error instead of clientError then? (let's define clientErrors as specific errors which must contain a client.id - assigned to some client) @mcollina

**Comment by mcollina** [comment]
That might a good definition!

**Comment by GavinDmello** [comment]
@behrad @mcollina Any of you guys working on this ? 
If not, I could do it and we can close this issue.

**Comment by mcollina** [comment]
go ahead, I'm not working on this.

**Comment by GavinDmello** [comment]
Any ideas on what this generic error would be called ?

**Comment by mcollina** [comment]
I would prefer if we always attach a client if one is not there (I assume we have a socket).

**Comment by behrad** [comment]
> I would prefer if we always attach a client if one is not there (I assume we have a socket).

However i think the value is in `client#id` not the client instance itself!
So if we don't know who is this error for, we shouldn't break `clientError` listeners' consistency with unknown clientIds
