### ISSUE TITLE
Latencies report strangely in pingpong.js

### ISSUE THREAD

**Issue by cefn** [mcollina/aedes#15]
I found myself inspecting the contents of the latencies array after seeing strange numbers reported. 

After a few numbers which look sensible, (though slow, assuming this should be interpreted in milliseconds), the following numbers seem to go a bit crazy. See this snapshot from different positions in the latencies array. I suspect this is to do with interactions between hrtime calls and convert-hrtime.

```
24 = 61.984865
25 = 61.991153
26 = 61.68552
27 = 60.849604
```

```
28 = 58343.782468
29 = 58343.993224
30 = 58343.974457
31 = 58342.961596
```

**Comment by mcollina** [comment]
There is a bug with the '#' subscription, it forwards $SYS topics right now. Possibly some bad things comes down and get parsed.
