### ISSUE TITLE
Packet callback is triggers multiple times, after client reconnects

### ISSUE THREAD

**Issue by kareha** [mcollina/aedes#150]
When I use this to receive a message from a client:

`aedesInstance.subscribe(topic, callback, done)`

The "callback" function is triggert multiple times for one message, when a client connects to the broker where it was connected before with the same topic and messages had been sent.

This:
`aedesInstance.on('publish', callback)`
on the other hand, is only triggered once at the same time.

The important part is: connect > send message to broker > disconnect > connect > send message to broker (this occurred multiple times)

Is this a know issue? Did I do something wrong?
Client connects with clean: true; all messages have retain: false

I use mqemitter-mongodb as mqemitter.

**Comment by mcollina** [comment]
Can you please make a code example so that I can reproduce?

Does it happen even without mqemitter-mongodb?

**Comment by kareha** [comment]
Of course:

Server:

```
var aedes = require('aedes')
var aedesInstance = aedes()

var mqttServer = require('net').createServer(aedesInstance.handle)
var port = 1883

mqttServer.listen(port, () => {
  console.log('Server listening on port', port)
})

aedesInstance.on('publish', function (packet, client) {
  console.log('Received (onPublish):', packet.payload.toString())
})

aedesInstance.on('client', function (client) {
  console.log('Client Connected:', client.id)

  var message = {
    cmd: 'publish',
    qos: 1,
    topic: '/request',
    payload: 'Hello',
    retain: false
  }

  aedesInstance.subscribe('/response', (packet, done) => {
    console.log('Received (by Subscription):', packet.payload.toString())
    done()
  }, () => {
    setTimeout(() => {
      aedesInstance.publish(message, (err, test) => {
        console.log('Published payload: ', message.payload)
      })
    }, 500)
  })
})

aedesInstance.on('clientDisconnect', (client) => {
  console.log('Client Disconnected:', client.id)
})
```

Client:

```
var mqtt = require('mqtt')

var options = {
  protocolVersion: 3,
  keepalive: 10,
  clean: true
}

var client = mqtt.connect('mqtt://localhost:1883', options)

client.on('connect', function () {
  console.log('connected')

  client.subscribe('/request', { qos: 1 }, (err, granted) => {
    console.log('subscribed /request')
  })
})

client.on('message', function (topic, message) {
  console.log('Received message: ', topic, message.toString())

  client.publish('/response', 'Hello back', { qos: 1 }, function () {
    console.log('Responded to message')
  })
})
```

**Console output:**

Server (client connects):

> Server listening on port 1883
> Client Connected: mqttjs_99048315
> Received (onPublish): mqttjs_99048315
> Published payload:  Hello
> Received (onPublish): Hello
> Received (by Subscription): Hello back
> Received (onPublish): Hello back

Server (client disconnects and connects again)

> Client Disconnected: mqttjs_99048315
> Received (onPublish): mqttjs_99048315
> Client Connected: mqttjs_f3ec7803
> Received (onPublish): mqttjs_f3ec7803
> Published payload:  Hello
> Received (onPublish): Hello
> Received (by Subscription): Hello back
> Received (by Subscription): Hello back
> Received (onPublish): Hello back

And again:

> Client Disconnected: mqttjs_f3ec7803
> Received (onPublish): mqttjs_f3ec7803
> Client Connected: mqttjs_6f899639
> Received (onPublish): mqttjs_6f899639
> Published payload:  Hello
> Received (onPublish): Hello
> Received (by Subscription): Hello back
> Received (by Subscription): Hello back
> Received (by Subscription): Hello back
> Received (onPublish): Hello back

"Received (by Subscription)" occurs multiple times, while "Received (onPublish)" only once like expected :-/

Thx in advance for help

**Comment by mcollina** [comment]
You are calling `subscribe` every time a client connects. You should do that at the top level, so that your function is only called once. 

MQTT is not a RPC system.

**Comment by kareha** [comment]
Ok, thx for that hint :)

But if I unsubscribe the topic when the client disconnects, it does not help either :(

```
aedesInstance.on('clientDisconnect', (client) => {
  console.log('Client Disconnected:', client.id)
  aedesInstance.unsubscribe('/response', function (packet, next) {
    next()
  }, () => {
    console.log('Unsubscribed topic')
  })
})
```

**Comment by mcollina** [comment]
If multiple clients connect concurrently, you will hid `aedes.subscribe` and  `aedes.unsubscribe` multiple times.

**Comment by kareha** [comment]
Yes that is ok. In the final code I have a different topic for each client, for example: /client/id123/response

My goal is to react on each client and create a request response procedure.

**Comment by mcollina** [comment]
you should use a wildcard and a top level subscription for that.

**Comment by kareha** [comment]
I found out the issue:

The topic was not deleted from the Qlobber tree on unsubscribe because it uses the callback function as the search pattern, and it was not the same in my case.

When I put the same callback at the unsubscribe parameter, everything works :)

See **responseHandler** here:

```
function responseHandler (packet, done) {
  console.log('Received (by Subscription):', packet.payload.toString())
  done()
}

aedesInstance.on('client', function (client) {
  console.log('Client Connected:', client.id)
  aedesInstance.subscribe('response', responseHandler, () => { ... })
})

aedesInstance.on('clientDisconnect', (client) => {
  console.log('Client Disconnected:', client.id)
  aedesInstance.unsubscribe('response', responseHandler, () => { ... })
})
```

Thx anyway
