### ISSUE TITLE
Handle multiple clients with same client ID

### ISSUE THREAD

**Issue by jyotman** [mcollina/aedes#153]
Currently if a second client tries to connect with a client ID that is already being used by some other client then Aedes disconnects the previous client and then connects the new client.

What I want to do is to retain the first client and un-authorise  the new client so the initial client remains intact.

To implement this I maintained a list of all the connected clients in a separate Redis instance. I added the client id to a Redis Set whenever a new client connected and removed that client id from the Redis Set if that client disconnected.

So in my `authenticate` method provided by Aedes, I wrote the following logic - 
On a new connection request, if a client with that client ID does not exist then allow the connection using `callback(null, true)` otherwise if the client ID already exists in the Redis Set then un-authenticate the client using `callback(null, false)`.

**Bug** - The problem is that when I un-authenticate the second client which is using the same client ID, then Aedes emits a disconnect event. Now this disconnect event causes 2 problems - 
1. I delete the client ID form my redis Set even though the first client with that same client ID is still connected.
2. Aedes too somehow thinks that the client with this client ID has been disconnected even though the first client is still successfully connected and has not received any disconnect event.

Now when I try to connect the second client again with the same client ID then it successfully connects as my Redis Set logic also fails and Aedes also fails to discover that the first client is still connected. As a result I have 2 clients connected to Aedes and both can successfully publish messages too.

**Comment by mcollina** [comment]
You should not support multiple client with different ids. The current behavior is by the MQTT spec, so you should work around that.

**Comment by mcollina** [comment]
@jyotman that's the behavior specified in the MQTT spec as far as I recall. Please check. If not, send a PR. This is really unspecified behavior, so I would not call that as a bug.
