### ISSUE TITLE
What is "backpressure"

### ISSUE THREAD

**Issue by buckle2000** [mcollina/aedes#154]
You mentioned "backpressure" in README, but seems like it is not a MQTT term.
Can you Explain that?

**Comment by mcollina** [comment]
It's a Node.js term. See https://nodejs.org/en/docs/guides/backpressuring-in-streams/.

**Comment by buckle2000** [comment]
Sorry, I read that but still don't understand what is "support backpressure". Can you explain that?

**Comment by buckle2000** [comment]
OK, so how is it related to `instance.subscribe/publish`?

**Comment by mcollina** [comment]
Aedes is built in such a way that only a limited amount of messages can be forwarded at any given time. This allows Aedes to pause the producers to avoid overloading the subscribers of messages.
