### ISSUE TITLE
mqtt.js client disonnected on error authorizeSubscribe result

### ISSUE THREAD

**Issue by alnikitich** [mcollina/aedes#155]
Hello!

When i check topic by authorizeSubscribe function in aedes like this:
```
aedes.authorizeSubscribe = function(client, sub, callback){
   ....
   return callback(Error("Wrong topic"));
}
```
mqtt.js client have disconnected and recconect after it.
but i should get error on client without disconnection

error result on authorizePublish disconnect client too.

Thank you.

**Comment by mcollina** [comment]
Return null as the second argument: https://github.com/mcollina/aedes/blob/master/README.md#authorizeSubscribe

**Comment by lixiaomeng8520** [comment]
@mcollina I also have this problem,  setting it to null does not work.  Mqtt.js invoke the close event.

**Comment by robertsLando** [comment]
@lixiaomeng8520  Check: https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#handler-authorizesubscribe-client-subscription-callback

**Comment by lixiaomeng8520** [comment]
@robertsLando 

I just want to get the sub error  in mqtt.js. Below is my client code: 

```js
client.subscribe('topic', {}, function (err, granted) {
     if (err) {
          console.log(err)  // never reached
     } else {
          console.log('sub success')
     }
})
```

**Comment by robertsLando** [comment]
@lixiaomeng8520 Based on MQTT specs you should not reveive the error there, instead you should check the granted qos of the subscription, if it is 128 it means the subscription has been rejected. Check suback response [here](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349323-)
