### ISSUE TITLE
sender on authorizeForward

### ISSUE THREAD

**Issue by alnikitich** [mcollina/aedes#161]
I have one topic for send and receive data (for group of clients)
and i want skip my own pushes (sendede from client) in authorizeForward function:

skip message forwarding if senderId  == client Id
but i haven`t senderId data.
i`ve tried add senderId in authorizePublish function? but i can`t add my own data to pushed packet.

how i can do it !?
thank you ! !

**Comment by mcollina** [comment]
This is not currently possible, the information is lost.
I would recommend you to not go into that path, but use a different topic for sending and one for receiving.
