### ISSUE TITLE
aedes persistance and mq

### ISSUE THREAD

**Issue by entcor** [mcollina/aedes#162]
Hello!
When i use persistance and mq together like this:

```
var persistence = aedesPersistenceRedis({...});
var mq = require('mqemitter-redis')({...})
var aedes = Aedes({
	mq: mq,
	persistence: persistence
});
```
I use mqtt.js as client.
My client  started on nodejs server.
 
my server not receive more then one push for one each topick from each client
and after it pushes have stoped.

when i remove mq or persistence form aedes config - everything work great.
I tried change persistence to mondodb persistence - i have this trouble too.

When i`m starting mqtt.js on webclient (in browser) everything work correctly.

**Comment by alnikitich** [comment]
i think it depends on multiple client subscription
i`m calling subscribe 3 times (for different topics)

**Comment by mcollina** [comment]
I'm lost, can you provide a full example of what is not working?

**Comment by cordovapolymer** [comment]
@alnikitich , I have tried to reproduce your issue with the following code, by running `bombing.js` and `bombingQoS1.js`, `ping-pong.js` with `throughputCounter.js` and `throughputCounterQoS1.js` from [benchmarks](https://github.com/mcollina/aedes/tree/master/benchmarks)
And could not reproduce it.

@mcollina The only thing is that when I tried a extensive benchmark by launching 4 bombingQos1.js and throughputCounterQoS1.js together with 1 bombing.js and 1 throughputCounter.js, 
without setting `concurrency: 0` I've got 
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 201 drain listeners added. Use emitter.setMaxListeners() to increase limit` and aedes stopped processing messages consuming 100% CPU. Is setting `concurrency: 0` a viable solution for such cases?

```
var aedesPersistenceRedis = require('aedes-persistence-redis')({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0,
  maxSessionDelivery: 100 // maximum offline messages deliverable on client CONNECT, default is 1000
})
var mq = require('mqemitter-redis')({
  port: 6379,          // Redis port
  host: '127.0.0.1',   // Redis host
  family: 4,           // 4 (IPv4) or 6 (IPv6)
  password: 'auth',
  db: 0,
  maxSessionDelivery: 100 // maximum offline messages deliverable on client CONNECT, default is 1000
})

var aedes = require('aedes')({persistence: aedesPersistenceRedis, mq: mq, concurrency: 0})
var server = require('net').createServer(aedes.handle)
var port = 1883

server.listen(port, function () {
  console.log('server listening on port', port)
})


```

**Comment by mcollina** [comment]
Does that happen without mqemitter-redis?

**Comment by cordovapolymer** [comment]
@mcollina , no it doesn't, when you run it like this:
`var aedes = require('aedes')({persistence: aedesPersistenceRedis})`

Also when you run it without mqemitter-redis with concurrency: 0 
`var aedes = require('aedes')({persistence: aedesPersistenceRedis, concurrency: 0})`
 , you get a `Maximum call stack size exceeded` in throughputCounter.js and throughputCounterQos1.js
:

```
received/s 81.60000000000001
received/s 166.8
received/s 0
received/s 0
received/s 0
events.js:155
EventEmitter.prototype.emit = function emit(type) {
                                           ^

RangeError: Maximum call stack size exceeded
    at MqttClient.emit (events.js:155:44)
    at MqttClient._handlePublish (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:905:12)
    at MqttClient._handlePacket (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:301:12)
    at process (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:257:12)
    at MqttClient.handleMessage (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:924:3)
    at MqttClient._handlePublish (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:906:12)
    at MqttClient._handlePacket (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:301:12)
    at process (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:257:12)
    at MqttClient.handleMessage (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:924:3)
    at MqttClient._handlePublish (/home/user/Documents/aedes-test/node_modules/mqtt/lib/client.js:906:12)
```

**Comment by mcollina** [comment]
Unfortunately I will not have time to look into this prior of mid-december :(. I'm sorry for any inconvenience.

**Comment by mchsk** [comment]
@gnought @mcollina 
Hey guys, I think this is just a `yes` / `no` question.

I have current setup:
```
  const mqemitter = require('mqemitter-redis')({
    port: redisConfig.port,
    host: redisConfig.host,
    family: 4,
    password: redisConfig.password,
    db: 0,
    maxSessionDelivery: 100
  })

  const persistence = aedesPersistenceRedis({
    port: redisConfig.port,
    host: redisConfig.host,
    family: 4,
    password: redisConfig.password,
    db: 0,
    maxSessionDelivery: 100,
    packetTTL: function (packet) {
      return 10
    }
  })
  const aedesOptions = {
    persistence,
    mqemitter,
  }

  const aedes = require('aedes')(aedesOptions)
  ...
```
When I run multiple instances of `aedes` (heroku) - when client connects, heroku router picks a dyno and with that client I can sub to a topic, publish to it, message is received.

When different client connects to different instance though, the first client never gets published messages.

I think I am missing something here. No errors anywhere in the logs.

Or what I expect here, is unfair expectaiton? Like publishing message on one instance, while subscriber on the other instance gets it? Thank you so much!

**Comment by behrad** [comment]
I think you are miss-naming configuration parameters:

```js
const aedesOptions = {
    persistence: persistence,
    mq: mqemitter,
  }

  const aedes = require('aedes')(aedesOptions)
```

**Comment by mchsk** [comment]
Oh yeah, the `mq` ! It seems it might work. Thanks @behrad!

**Comment by lizzymendivil** [comment]
hey @mchsk could tell me please, what does mean *db: 0* in your mqemitter  configuration? Thanks.

**Comment by robertsLando** [comment]
@lizzymendivil that's a typo, It doesn't mean nothing as both aedes-persistence-redis and mqemitter-redis doesn't accept a db param
