### ISSUE TITLE
keep alive timeout exception

### ISSUE THREAD

**Issue by syberkitten** [mcollina/aedes#165]
Constantly getting this keep alive error:
```
msg":"keep alive timeout","type":"Error","stack":"Error: 
keep alive timeout\n    
at keepaliveTimeout (/home/ubuntu/apps/my-server/node_modules/aedes/lib/handlers/connect.js:44:28)\n    
at Timeout.timerWrapper [as _onTimeout] (/home/ubuntu/apps/my-server/node_modules/aedes/node_modules/retimer/retimer.js:21:16)\n   
at ontimeout (timers.js:386:14)\n    
at tryOnTimeout (timers.js:250:5)\n    
at Timer.listOnTimeout (timers.js:214:5)

```

will try decrease the heart beat interval and see if it makes any difference

**Comment by GavinDmello** [comment]
what's the keepAlive on the mqtt client ?

**Comment by syberkitten** [comment]
The 'heartbeatInterval' is set to 30000

**Comment by cordovapolymer** [comment]
I'm constantly getting the keepAlive timeout as well. It's normal when client has got a connection lag.

**Comment by GavinDmello** [comment]
@syberkitten Closing this for now. Reopen if needed.

**Comment by hutje** [comment]
Still have this problem when there are more than 20 clients connected... What's the problem?

**Comment by robertsLando** [comment]
@hutje The client keepalive is set with client `connect` request (see mqtt [connect](https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options) keepalive option). If you get that message it means that aedes isn't receiving any message (ping, publish or whatelse) from this client in the that period

**Comment by hutje** [comment]
> @hutje The client keepalive is set with client `connect` request (see mqtt [connect](https://github.com/mqttjs/MQTT.js#mqttclientstreambuilder-options) keepalive option). If you get that message it means that aedes isn't receiving any message (ping, publish or whatelse) from this client in the that period
> 
> Reference in code:
> 
> Keep alive setup on connet:
> https://github.com/moscajs/aedes/blob/master/lib/handlers/connect.js#L142
> 
> Keep alive update at every request:
> https://github.com/moscajs/aedes/blob/master/lib/handlers/index.js#L65

I think I figured it out. Sometimes the wifi-strength is not high, -80dBm and this causes the PINGREQ to have trouble to send a message without delay. The delay isn't a problem for the messages I send, but it does for the KeepAlive timeout when there is no topic message being sent.
I will change the KeepAlive timeout on my esp8266 to 60 seconds and manually send some package every 45 seconds. This way the timeout does not trigger.

**Comment by robertsLando** [comment]
> I will change the KeepAlive timeout on my esp8266 to 60 seconds and manually send some package every 45 seconds

I suggest to set a keepalive that is 2/3 times your ping. For example: keepalive 90 seconds and send a pingreq every 30 sec

**Comment by Anasnew99** [comment]
#
