### ISSUE TITLE
emitPacket sets retain = false, before emitting the event via on('publish')

### ISSUE THREAD

**Issue by syberkitten** [mcollina/aedes#166]
I'm hooking up to the aedes.on('publish') event,
and retain is always false.

I found this to be a behaviour in this code:
https://github.com/mcollina/aedes/blob/ecdd0cc03247febc46edbf5d0dbbc527ce5477ec/aedes.js#L149
```
this.packet.retain = false
this.broker.mq.emit(this.packet, done)
```

Which seems peculiar since it changes the original state of the published message.

causing the emitted packets to always be retain = false,  while the original message
might be with retain set to true.

I've changed this behavior on my fork of Aedes by commenting
out the line, and changing the expected retain property in affected tests.

Since we are using the on('publish') for logging purposes, knowing the published packets
original retained state make sense.

At any rate I don't see a reasoning for this, 
would love to learn what is behind this decision .. ?

**Comment by mcollina** [comment]
@syberkitten the `retain` property needs to be false when delivering the message by the spec. We can probably fix this behavior by setting `packet.retain = false` when a packet is received by an Aedes instance.

Would you like to attempt this fix?

**Comment by syberkitten** [comment]
@mcollina Are you referring to this spec guideline?: 
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html
```
When sending a PUBLISH Packet to a Client the Server MUST set the RETAIN flag to 1 if a message is sent as a result of a new subscription being made by a Client [MQTT-3.3.1-8]. It MUST set the RETAIN flag to 0 when a PUBLISH Packet is sent to a Client because it matches an established subscription regardless of how the flag was set in the message it received [MQTT-3.3.1-9].
```

It becomes clearer that the distinction is such:

- if client A publishes a retained = 1 message while client B is connected, B should get this message as retained = false, because it got it directly.
- if client A publishes a retained = 1 message while client B is offline, when B re-connects
the message should be received as retained = 1.

This distinction allows knowing if the other side is actually - online or not,
or in mqtt terms, if the message was waiting on the the topic (retained) 
or transmitted directly.

If we are clear on this it would be easier to go further ....

**Comment by syberkitten** [comment]
Therefore If the broker .emit('publish') is used only for external layers (logging / api etc)
then it makes sense to leave the retained flag as it was passed by the publishing client.

On the other hand, if the broker .emit('publish') is used internally, we have a problem
as the architecture needs to support the above distinction (thus state of packet.retain changes)
when getting to the client if the client is connected. (retain is set to false)

Is it clear what m trying to get to?

**Comment by mcollina** [comment]
> Therefore If the broker .emit('publish') is used only for external layers (logging / api etc)
then it makes sense to leave the retained flag as it was passed by the publishing client.

This is the case.

We are currently supporting the behavior described in the paragraph you are referring to. The retained flag is added when sending retained messages.

**Comment by GavinDmello** [comment]
@mcollina We could circumvent this issue by creating a new object and calling `emitPacket` and passing the original packet down to `callPublished`.  I believe I had suggested something similar before.

**Comment by mcollina** [comment]
I think this issue can be closed, it was open in 2017. We can reopen if it's still an issue.

**Comment by GavinDmello** [comment]
Fair enough. Closing this. @syberkitten feel free to reopen if it's still an issue.
