### ISSUE TITLE
Question: forwarding selectively messages to clients from another broker

### ISSUE THREAD

**Issue by muka** [mcollina/aedes#167]
Hi,
this is a question not really an issue. Hope this is ok to place it here also for future reference

I have an use case where I want `aedes` to forward messages from another broker, selectively forwarding messages based on some client details.

I would like to expose aedes to internet with custom auth/authz and send to specific clients only the messages that they can receive.

I have already implemented it by filtering subscriptions topic based on pattern, but from an user perspective get complex as one has to know exactly what to subscribe for ahead of time eg.`app/1` is ok but `app/+` is not

Example use case:
1. topics are like `app/[id]` 
2. `client1` subscribe to `#` but can access only `app/[id=1,2]`
3. `magic happens`
4. `client1` receive just those messages

What I did so far
-  `authenticate()` perform a login and fetch locally all the required details for a client and store it in the client object.
- an mqtt client for `broker1` and one for `aedes` that publish based on the details in the client.
- `authorizeForward()` lookup in the cache by client id and decide if the message can be forwarded or not

I tried also to use `aedes.publish({...})` or `aedes.mq.emit({ ... })` but those seems not to work as I need (publish doesn't  show up in the `auth*` callback, emit just publish to all clients)

Is there a better approach in this case?

Thank you!

**Comment by mcollina** [comment]
I am a bit lost, it’s not clear how you would like to achieve this.

I would also recommend that you should not violate the MQTT spec in your implementation.

**Comment by muka** [comment]
When a msg from an internal broker is received it is published to aedes. On `authorizeForward` the client details (stored at login) are used to decide whether to allow or not the forward.

Do you see a violation of MQTT  spec in this approach?

Thank you

**Comment by mcollina** [comment]
That would also be very slow, however it's probably the closest thing you can do to what you want to do.

**Comment by muka** [comment]
I see, thank you
