### ISSUE TITLE
Broker should store also subscriptions with QoS 0

### ISSUE THREAD

**Issue by mitsos1os** [mcollina/aedes#174]
This is a port from the issue in mosca:
https://github.com/mcollina/mosca/issues/693

It should be adjusted accroding to MQTT spec here as well

**Comment by cordovapolymer** [comment]
@mitsos1os , can you check if it now works with my patch?

**Comment by mitsos1os** [comment]
I haven't really dealt with aedes in general (still using mosca), but I believe this should be enough for a fix.
However patches should be also made to other aedes repositories like: **aedes-persistence-level**, **aedes-persistence**

**Comment by mcollina** [comment]
Yes they should. Would you like to send PRs?

**Comment by GavinDmello** [comment]
@mitsos1os This can be closed with the latest changes on aedes-persistence-mongodb. I don't think this should happen with other persistences. Feel free to reopen just in case.
