### ISSUE TITLE
On reconnect: recive only new message

### ISSUE THREAD

**Issue by psummo** [mcollina/aedes#175]
I have the same problem that I had with mosca
The problem is:
On reconnect, client recive all message, also message that was already recived when client was online.
Example
**CLIENT A** & **CLIENT B** ONLINE
**CLIENT A** --> _SEND MESSAGE 1_--> **CLIENT A/B** REVICE MESSAGE 1
**CLIENT B** --> _DISCONNECT_
**CLIENT A**--> _SEND MESSAGE 2_--> **CLIENT A** REVICE MESSAGE 2
**CLIENT B** --> _RE CONNECT_ --> **CLIENT B** RECIVE MESSAGE 1/2
But client B should recive only MESSAGE 2: correct?

 [This is broker Aedes code](https://pastebin.com/eC3vbRdA)

**Comment by mcollina** [comment]
Can you please add the client you are using for this?

**Comment by psummo** [comment]
I use xamarin forms with package Mqtt from xamarin.

https://pastebin.com/xDR1RNfM

**Comment by mcollina** [comment]
This does not publish the message.

Can you create a test case with MQTT.js or mqtt-packet? thanks.

**Comment by psummo** [comment]
I'm not able to set a CLIENT ID so everytime I restart Subscription.js CLIEND ID change and I can't understand if function or not

**Comment by psummo** [comment]
I try with this 2 simple Publisher.js and Subcriber.js and if
Subscriber is not launched and Publisher send messages, when Subscriber run I recive only the last message

Publisher
```
var mqtt    = require('mqtt');
var client  = mqtt.connect({port: 1883, host: "localhost", clientId : "pluto"})

client.on('connect', function () {
    client.publish('presence', 'message5!', {retain: true, qa: 1});
    client.end();
});
```
Subscriber
```
var mqtt    = require('mqtt');
var client  = mqtt.connect({port: 1883, host: "localhost", clientId : "ciccio"})

client.on('connect', function () {
    client.subscribe('presence');

    client.on('message', function (topic, message) {
        console.log(message.toString());
    });
});
```

I don't know how to set persistance to subscription from MQTT.js so I need to subscribe client at every run

**Comment by mcollina** [comment]
If you publish with retain, you will get the data at every subscription.
Il giorno ven 15 dic 2017 alle 12:43 Pierluigi Summo <
notifications@github.com> ha scritto:

**Comment by psummo** [comment]
Retain is used for save the message in db? 
But this MQTT.js situation is different.
On xamarin I do a persistent subscription and I don't do the subscription to the same topic. And I recive ALL topic message.
Here I try with 
- persistance TRUE --> Recive only last message  when Subscriber turn online
- persistance FALSE --> Recive only last PERSISTANT message if there's any
In my case, in xamarin
- subscribe with qos = 0
- publish message with qos = 1 and retain = true

**Comment by mcollina** [comment]
publish with retain false, and set the clientId to the same value

**Comment by psummo** [comment]
clientID? 
I have only this 3 string

**Connection to broker**
` await emitter.ConnectAsync(new MqttClientCredentials(NickNameEntry.Text), null, false);`
First value) MqttClientCredentials(NickNameEntry.Text) is ClientID
Second value) MqttLastWill=null
Third value) cleanSession = false

**Subscribe to topic**
`await emitter.SubscribeAsync(RoomName.Text, MqttQualityOfService.AtMostOnce);`
First value) topic name
Second value) QOS = 0

**Send message**
`await emitter.PublishAsync(MessageToSend, MqttQualityOfService.AtLeastOnce, true);`
First value) message in byte[ ]
Second value) QoS = 1
Third value) Retain = true

Ok, I will change retain to "false", but clientID? to false where?

**Comment by mcollina** [comment]
`clientId` should be `NickNameEntry.Text`, but it should not change between connects.

**Comment by psummo** [comment]
Ok, I try always with same nickname. I use and EditorText only for test on different device, but nickname not change. So I try only change retain to false.

**Comment by psummo** [comment]
Now at reconnect any message will publish. It's a Qos Problem?

**Comment by mcollina** [comment]
what do you mean?

**Comment by psummo** [comment]
I subscribe client with QoS = 0 and Publish with QoS = 1

**Comment by mcollina** [comment]
You should be doing QoS 1 on both sides.

**Comment by psummo** [comment]
Now with retain false, QoS = 1 publish/subscribe come again all message also if I have read it when I was online

**Comment by mcollina** [comment]
is this happening without MongoDB?

**Comment by psummo** [comment]
Nono mongodb is working, I search in it and subscription/outgoing/emitters exist and there are all data.

**Comment by mcollina** [comment]
Try a) without MongoDB and b) with MQTT.js.

**Comment by psummo** [comment]
without mongo on xamarin and on MQTT.js doesn't recive all message, doesn't recive any message.

**Comment by mcollina** [comment]
Very likely you are doing something wrong. I would recommend you to read about the MQTT protocol and its configuration.

https://www.hivemq.com/mqtt-client-library-encyclopedia

**Comment by psummo** [comment]
I have already read different thread (hivemq include). I don't think that was different

Server Aedes
```
var aedes = require('aedes')()
var server = require('net').createServer(aedes.handle)

var port = 1883

server.listen(port, function () {
    console.log('server listening on port', port)
})

aedes.on('clientError', function (client, err) {
    console.log('client error', client.id, err.message, err.stack)
})

aedes.on('publish', function (packet, client) {
    if (client) {
        console.log('message from client', client.id)
    }
})

aedes.on('subscribe', function (subscriptions, client) {
    if (client) {
        console.log('subscribe from client', subscriptions[0].topic, client.id);
    }
})

aedes.on('client', function (client) {
    console.log('new client', client.id)
})
```
Publish Client
```
var mqtt    = require('mqtt');
var client  = mqtt.connect({
    port: 1883,
    host: "localhost",
    clientId : "PUBLISHER",
    protocolId: 'MQIsdp',
    protocolVersion: 3})

client.on('connect', function () {
       client.publish('Chat', "Ciccio", {retain: false, qos: 1});
       client.end();
});
```
Subscriber
```
var mqtt    = require('mqtt');
var client  = mqtt.connect({
    port: 1883,
    host: "localhost",
    clientId : "SUBSCRIBER",
    protocolId: 'MQIsdp',
    protocolVersion: 3})

client.on('connect', function () {
    client.subscribe('Chat', {qos : 1});

    client.on('message', function (topic, message) {
        console.log(message.toString());
    });
});
```
If subscriber is online recive message without problem from publisher. If subscriber is offline and publisher publish something, on reconnect nothing will recive

**Comment by mcollina** [comment]
you must pass clean: false to connect()
Il giorno ven 15 dic 2017 alle 19:45 Pierluigi Summo <
notifications@github.com> ha scritto:

**Comment by psummo** [comment]
Ok now work. I think is a problem of client xamarin? Possible? I try with M2MTTQ that was described in hivemq and write here :) Thanks a lot @mcollina
