### ISSUE TITLE
aedes ready for mosca replacement?

### ISSUE THREAD

**Issue by mitsos1os** [mcollina/aedes#176]
Hi, this is not an actual issue.
I just wanted to ask whether **aedes** is at a stable enough state to be used in production and replace **mosca**.

We currently use **[mosca](https://github.com/mcollina/mosca)** for a platform we are developing. I could say we are pretty happy with it and also performance wise (since we do not have such a big number of MQTT clients so that it hangs), it suits our needs.

Lately however, some buggy behavior started appearing that cannot be 100% reproduced. Check the issue reported [here](https://github.com/mcollina/mosca/issues/713)

What is your opinion? Is Aedes ready for a full mosca replacement?

**Comment by mcollina** [comment]
It is written to be.

I do not feel comfortable in _fixing bugs_ in the Mosca codebase anymore. I cannot get the unit test suite to run on Node 8 or Node 9 for example.
If Aedes needs to be hardened to be brought to the same level, I'd recommend to send PRs to the various Aedes components to harden them. (MongoDB components are less stable than the redis ones).

**Comment by mitsos1os** [comment]
Ok... thank you for your response

**Comment by tripflex** [comment]
I was looking at this as well, switching from Mosca to Aedes, but I did find one issue regarding MongoDB that could be an issue with scaling if necessary later on:
https://github.com/mcollina/aedes/issues/159

**Comment by syberkitten** [comment]
If It might illuminate certain corners, the limitation
of Aedes is mainly in the lack of clustering,
which in best of breed brokers (mostly in Erlang) is managed by dedicated actors
managing the communication between brokers, which is whole area
of work.

My redis implementation of Aedes (using the redis persistence) works well
up until the need to connect broker instances across datacenters.

After some words with @mcollina revealed that Redis replication is a logical
route to explore given that Redis persistence is more mature and accurate 
to the task of being the persistence layer for a broker, having pub/sub
ttl, the in memory and other goodies.

The only problem was... Current redis replication systems do not
replicate the pub/sub keys. (not [Dynomite](https://github.com/Netflix/dynomite) and not [Redis Cluster](https://redis.io/topics/cluster-spec))

I believe that within the coming year there will be better Redis replication
solutions to try this again, but for now I'm using a different broker that supports
multiple broker instances (on different data centers)
