### ISSUE TITLE
program will be exit when stream throws Error: write EPIPE

### ISSUE THREAD

**Issue by pysjp** [mcollina/aedes#178]
Error msg as follows:

0|mqtt     | Error: write EPIPE
0|mqtt     |     at _errnoException (util.js:1024:11)
0|mqtt     |     at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)

**Comment by mcollina** [comment]
Can you reproduce? Can you upload a script so I can check what’s happening?

**Comment by GavinDmello** [comment]
@pysjp @mcollina I think this happens while writing to dead connections.

**Comment by mcollina** [comment]
are we removing an error handler too early? In which condition this happens?

**Comment by GavinDmello** [comment]
@mcollina In my case it usually happened when sending packets downstream , but the process didn't exit . Maybe because I was listening to Aedes' error event.

**Comment by mcollina** [comment]
would you attempt a fix?

**Comment by GavinDmello** [comment]
Yes. Let me have a look

**Comment by GavinDmello** [comment]
@pysjp How many clients are you trying to connect? 

@mcollina <a>https://github.com/mcollina/aedes/blob/master/lib/client.js#L73 </a>
Could we attach this handler earlier  ?

**Comment by mcollina** [comment]
Yes, we can move it before nextBatch()

**Comment by pysjp** [comment]
[mqtt.js.zip](https://github.com/mcollina/aedes/files/1584586/mqtt.js.zip)
Thanks for your replys
@GavinDmello it may be 30K connections in one broker server，I use pm2 and it restart when attach this error。and all error logs as follows：
(node:17004) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 201 drain listeners added. Use emitter.setMaxListeners() to increase limit
(node:17004) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 201 drain listeners added. Use emitter.setMaxListeners() to increase limit
Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
@mcollina attach
[mqtt.js.zip](https://github.com/mcollina/aedes/files/1584587/mqtt.js.zip)
 file is my start script file,it's very simple

**Comment by cordovapolymer** [comment]
@pysjp @mcollina Maybe the root of the issue is the same with https://github.com/mcollina/aedes/issues/162#issuecomment-344674189

**Comment by mcollina** [comment]
Try 0.32.1 and let us know, it should fix it!
