### ISSUE TITLE
TLS Options while creating sever

### ISSUE THREAD

**Issue by chiradip** [mcollina/aedes#18]
How can I use PFX option as in regular NodeJS TLS 
Like the following.
var options = {
  pfx: fs.readFileSync('client.pfx')
};

Besides pfx/pkcs, the following parameters are necessary to have at the minimum -  crl, passphrase, requestCert, rejectUnauthorized. Ideally the whole TLS options should be available in the same way regular TLS options work. If already possible - please provide an example.

**Comment by mcollina** [comment]
Aedes is _just_ a module. Mosca will adopt Aedes soon, and these will be provided there.
You can roll those by using the `tls` module yourself: Aedes works on any stream server.
