### ISSUE TITLE
Will message not removed from persistence after publish

### ISSUE THREAD

**Issue by emilianobonassi** [mcollina/aedes#180]
I'm experiencing this issue that it's causing db size to grow.

I see that in the client finish [logic](https://github.com/mcollina/aedes/blob/master/lib/client.js#L241) the **LWT** is not deleted.

The [spec](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/csprd02/mqtt-v3.1.1-csprd02.html) imposes it in the mandatory normative statement **MQTT-3.1.2-10**.

Is it a desidered behaviour or I'm missing something?

**Comment by GavinDmello** [comment]
@emilianobonassi what persistence are you using ?

**Comment by emilianobonassi** [comment]
`aedes-persistence-redis`

**Comment by GavinDmello** [comment]
Nice catch!

**Comment by emilianobonassi** [comment]
Thanks @GavinDmello. 

To be clear, the issue doesn't depend on the particular version of `aedes-persistence` used.

**Comment by GavinDmello** [comment]
Yep. I can confirm that .

**Comment by behrad** [comment]
👍
