### ISSUE TITLE
aedes un abnormity

### ISSUE THREAD

**Issue by weiliudong** [mcollina/aedes#184]
I ran Aedes in my project. After a period of time, Aedes could only subscribe to not be able to publish messages to the client. I didn't find the reason for a long time after checking it for a long time. By checking Linux server memory, program process and a series of normal, I was very sad.
var aedes = require('aedes')();
var server = require('net').createServer(aedes.handle);
var port = 1883;
server.listen(port, function () {
    console.log(port);
});
aedes.on('client', function (client) {
    console.logclient.id);
});
aedes.on('clientError', function (client, err) {
    console.error(client.id, ' +', err);
});
aedes.on('publish', function (packet, client) {
    if (client) {
        console.log(client.id, packet.topic);
    }
});
aedes.on('subscribe', function (packet, client) {
    console.log(client.id, 'subscribe', packet[0].topic);
});
module.exports = aedes;

**Comment by weiliudong** [comment]
I use the PM2 management program, I run PM2 restart after the broker can work

**Comment by cordovapolymer** [comment]
@weiliudong what version of node do you use?

**Comment by weiliudong** [comment]
The node environment for the server running is v8.9.4,The version of PM2 is 2.9.1,Are you suspicious of these problems in my present environment?

**Comment by weiliudong** [comment]
@cordovapolymer Currently updated to aedes@0.33.0,Do it run for a period of time to see if it will be reproduced.
