### ISSUE TITLE
source ip of client

### ISSUE THREAD

**Issue by izarraga** [mcollina/aedes#186]
Is posible to see ip and port of client when connect ?

In autentication maybe it would be interesting.

**Comment by mcollina** [comment]
The TCP socket (or TLS) is available at https://github.com/mcollina/aedes/blob/master/lib/client.js#L22. Would you mind sending a PR to update the docs?

**Comment by izarraga** [comment]
It seems simple but I can not find the ip
console.log(require('util').inspect(client.conn, {showHidden: true, depth: null}));

**Comment by mcollina** [comment]
@izarraga are you using TCP, TLS, WS or WSS?

**Comment by izarraga** [comment]
TCP(internal) and TLS(external)

// SERVIDOR MQTT

var server = require('net').createServer(aedes.handle);
var port = 1883;

server.listen(port,"0.0.0.0", function () {
  console.log('server listening on port', port);
})


// SERVIDOR MQTT SOBRE TLS

var tls_options = {
    key: require('fs').readFileSync('/root/aedes/mqtt_server.key'),
    cert: require('fs').readFileSync('/root/aedes/mqtt_server.crt'),
//  ca: fs.readFileSync('ca.crt'),
    requestCert: false,
    rejectUnauthorized: false
};

var server_tls = require('tls').createServer(tls_options, aedes.handle);

var tls_port = 8883;

server_tls.listen(tls_port, "0.0.0.0", function () {
    console.log('server_tls listening on port', tls_port);
})

**Comment by mcollina** [comment]
`client.conn` will be an instance of https://nodejs.org/api/tls.html#tls_tlssocket_remoteaddress should contain the information.

**Comment by izarraga** [comment]
Thanks, is OK
client.conn.remoteAddress

**Comment by btsimonh** [comment]
if you have both ws: and mqtt running (two servers), then something like:

```
          if (client.conn.remoteAddress){
            client.ip = client.conn.remoteAddress;
          }
          if (client.req){
            if (client.req.socket){
              client.ip = client.req.socket.remoteAddress;
            }
            if (client.req.rawHeaders){
              for (let i = 0; i < client.req.rawHeaders.length; i++){
                if (client.req.rawHeaders[i] === 'x-forwarded-for'){
                  client.ip = client.req.rawHeaders[i+1];
                  break;
                }
              }
            }
          }
          console.log("Connection source ip " + client.ip);
```

works to get the ip of the client.
My setup is behind haproxy as well (wss->ws), hence looking for a 'x_forwarded_for' header.  There are probably better ways of getting the headers, but I did not find a pre-decoded version (yet).

**Comment by nolimitdev** [comment]
@btsimonh you do not need complicate it using `client.req.rawHeaders` because of `client.req` is `IncomingMessage` which has `headers` field : https://nodejs.org/api/http.html#messageheaders so simply use `client.req.headers['x-forwarded-for']`
