### ISSUE TITLE
Clients are not notified about server disconnect on process terminate

### ISSUE THREAD

**Issue by CyanoFresh** [mcollina/aedes#188]
Hello. I am using this library with websocket stream for browser clients. Thanks for your work, all works properly but I found this problem on production server (ubuntu 16.04):
1. Server (mqtt+websocket) starts
2. Client connects to mqtt, subscribes to topics, etc.
3. Server process is terminated (Ctrl + C or other)
4. Client is not notified about it (disconnect event) and says that connection is open for it

At the same time another browser client that was connected by websockets gets notified about it (disconnect event). When server runs on my dev PC (windows 10) all works properly. Tried different mqtt clients - same problem. What can be a problem? Is it ubuntu-related issue?

**Comment by GavinDmello** [comment]
Have you tried the `offline` and  `close` events from mqtt.js  ?

**Comment by CyanoFresh** [comment]
Browser (mqtt.js) clients are working fine. MQTT clients don't receive this events

**Comment by CyanoFresh** [comment]
Sorry, there is a bug in my mqtt client (mqttfx)
