### ISSUE TITLE
Aedes agent message sent to the terminal confirmation

### ISSUE THREAD

**Issue by weiliudong** [mcollina/aedes#189]
Hello everyone
  I put up a Aedes agent on the server side. I want to know from the agent whether the message has been sent to the terminal device. What is the way to get the confirmation message directly?

**Comment by weiliudong** [comment]
From this website, https://github.com/mcollina/mosca/wiki/Mosca-advanced-usage can find Mosca's message confirmation, but in Aedes API, I can't find which one. Does Aedes have this event?

**Comment by mcollina** [comment]
There is an `'ack'` event for QoS 1 and Qos 2 messsaged.
