### ISSUE TITLE
How about mosca and aedes?

### ISSUE THREAD

**Issue by DayTimeDreamer** [mcollina/aedes#190]
Hi, We are developing an IM APP using mosca, but it has some issues. Will aedes be better than mosca?

**Comment by behrad** [comment]
Aedes' design is improved

**Comment by DayTimeDreamer** [comment]
Our project will be delivered at the beginning of next month. Could give me an example that how to set up a server with mongodb please? Thank you!

**Comment by behrad** [comment]
You can find samples in aedes-persistence-mongo repo

**Comment by DayTimeDreamer** [comment]
Is aedes ready for production ? @behrad

**Comment by behrad** [comment]
I can't tell for mongo-persistent, but for the Redis one YES

**Comment by MrSpark2591** [comment]
@behrad now is it production ready for mongo-persistent?

**Comment by behrad** [comment]
I am not using mongo-persistent @MrSpark2591

**Comment by mcollina** [comment]
I fixed a memory leak recently.

**Comment by avanderpluijm** [comment]
> Aedes' design is improved

Does this mean that aedes is preferred over mosca for a new project? (is/will mosca deprecated?)

**Comment by gnought** [comment]
Aedes has decoupled its persistence store and mqemitter be a separate component. You could use different stores to store retained messages and QoS persistence, while you could also make use of different mqemitters with back pressure and create cluster-enabled aedes. There will be more bug fix and improvements coming. Test it as much as possible and submit any issues you found. 😄
