### ISSUE TITLE
How to get username and password in authorizeSubscribe function?

### ISSUE THREAD

**Issue by bobvanluijt** [mcollina/aedes#191]
Is it possible to get the username and password in the `authorizeSubscribe` function?

Reason for asking is that I want to validate if somebody has access to publish or subscribe based on the username and password used to authenticate.

**Comment by mcollina** [comment]
you will need to store them somewhere (Attach them to the client maybe) during the authentication call.

**Comment by FIRAT-URASLI** [comment]
`aedes.authorizeSubscribe = async function (client, sub, callback) {
    
    console.log(client._parser.settings.username)

}`
