### ISSUE TITLE
Authentication Client Errors

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#203]
Aedes is not emitting mqtt connect errors like authentication errors: https://github.com/mcollina/aedes/blob/275bda32461ea8053c8610b8a3e5b6f0f838f1b6/lib/handlers/connect.js#L67-L83

How is this supposed to be done @mcollina ?
I'm suggesting emitting `clientError` with the specific error.

**Comment by behrad** [comment]
Apps may want to log `not authorized` events...

**Comment by mcollina** [comment]
Ok, would you like to send a PR for that?
