### ISSUE TITLE
Topic rewrite on forward gives weird behavior

### ISSUE THREAD

**Issue by num-lock** [mcollina/aedes#207]
I am trying to implement something like namespaces within my broker implementation.

* two clients (c1, c2) in first namespace (n1)
* two more clients (c3, c4) in second namespace (n2)

The mapping is done via client id, e.g. `f(c2)=n1`.

On `authorizePublish` and `authorizeSubscribe` I prepend the namespace to the topic, e.g. c1 publishes to `test/a` the topic gets rewritten to `n1/test/a`. Same for subscribe. This works.

Goal: c1 and c2 can naturally publish and subscribe to each other using arbitrary topics without conflicting c3 and c4 and vice versa in this case.

However, when clients receive messages they will get the rewritten topic, e.g. c1 receives messages from `n1/test/a` instead of `test/a`. The latter is what it actually subscribed to and what I want in the actual packet.

I tried to strip off the namespace with `authorizeForward`:

```js
broker.authorizeForward = (client, fwd) => {
    const parts = fwd.topic.split('/');
    parts.shift();    
    fwd.topic = parts.join('/');
    return fwd;
};
```

This works as long as one client is subscribed and publishing to a topic. For each new client the calls to `authorizeForward` stack on top of each other, e.g. c1 receives `test/a` and c2 gets `a`.

I doubt this is the desired behavior of `authorizeForward`?

**Comment by num-lock** [comment]
Since the same packet object seems to get passed around synchronous on each forward in a sequential way I implemented this quick fix in my code:

```js
broker.authorizeForward = (client, fwd) => {
    if (!fwd.modded) {
        const parts = fwd.topic.split('/');
        parts.shift();
        fwd.topic = parts.join('/');
        fwd.modded = true;
    }
    return fwd;
};
```

Still not sure if `authorizeForward` is supposed to behave this way.

**Comment by mcollina** [comment]
Something that you can do in `authorizeForward` which will be the best behavior is to produce a new packet using https://github.com/mcollina/aedes-packet.

Let me know how this goes.

**Comment by num-lock** [comment]
I think my problem really comes from a misunderstanding in the purpose of this function, or rather a misuse for my use-case. For example when there are no subscribers to a topic and only publishers `onForward` does not get called. Thinking about this makes sense. When there are subscribes it gets called. If I create a new packet or manipulate the given one, either way the side effect I introduce here gets all the way down to things like `aedes.on('publish')`. But only if there is at least one subscriber. Not sure where to correctly re-rewrite the topic (strip off the namespace again) in my implementation with this behavior but this is not part of this issue. Actually this appears to be no issue at all.
