### ISSUE TITLE
Node red - Connection failed to broker

### ISSUE THREAD

**Issue by nospam2k** [mcollina/aedes#218]
I can't seem to connect to Aedes. MacOS Mojave. Node.js 10.12.0. 

Mqtt code as function in Node-red:
var aedes = global.get('aedes');
var net = global.get('net');
var port = 1883
var server = net.createServer(aedes.handle);
   
server.listen(port, function () {
    console.log('server listening on port', port)
})

Using an MQTT node I get "Connection failed to broker: MQTT://server:1883"

Is there a way to use this with node-red?

**Comment by mcollina** [comment]
I think you might put the IP address in place of ‘server’ in node-red.

**Comment by mcollina** [comment]
I think you might put the IP address in place of ‘server’ in node-red.

**Comment by nospam2k** [comment]
I did use the ip as well. This works just as a node.js script. Just not in node-red.

**Comment by mcollina** [comment]
How are you connecting to the server?

Try:

```js
server.listen(port, function (err) {
  if (err) {
   console.log(err)
  return
  }
  console.log('server listening on port', port)
})
```

Maybe there is an error when listening.

**Comment by nospam2k** [comment]
Node-red:
16 Oct 09:07:14 - [info] Starting flows
16 Oct 09:07:14 - [info] Started flows
16 Oct 09:07:14 - [info] Server now running at http://127.0.0.1:1880/
server listening on port 1883

Mosquitto:
mosquitto_sub -d -v -h 127.0.0.1 -t '#'
Client mosqsub|891-daf sending CONNECT

But running as node.js:
node aedes-mqtt-broker.js 
server listening on port 1883

mosquitto_sub -d -v -h 127.0.0.1 -t '#'
Client mosqsub|885-daf sending CONNECT
Client mosqsub|885-daf received CONNACK (0)
Client mosqsub|885-daf sending SUBSCRIBE (Mid: 1, Topic: #, QoS: 0)
Client mosqsub|885-daf received SUBACK
Subscribed (mid: 1): 0

**Comment by mcollina** [comment]
I think it's related to node-red, not this module.

**Comment by nospam2k** [comment]
I agree. But Mosca seems to have a few outdated vulnerable dependencies and their seems to be no other option for mqtt broker in node-red. It would be nice to get this to work if possible.

**Comment by nospam2k** [comment]
I'd like to continue debugging this if you might help. It seems like net is returning the packet into node-red but aedes.handle isn't working. 

Here is what server.listen is returning:
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 1,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 1,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 968,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 2,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 2,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 988,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 3,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 3,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 1013,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 4,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 4,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 1033,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 5,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 5,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 1070,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 6,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 6,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 1095,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }
client connected
Socket {
  connecting: false,
  _hadError: false,
  _handle:
   TCP {
     reading: true,
     onread: [Function: onStreamRead],
     onconnection: null,
     [Symbol(owner)]: [Circular] },
  _parent: null,
  _host: null,
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: null,
     ended: false,
     endEmitted: false,
     reading: true,
     sync: false,
     needReadable: true,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     emitClose: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: true,
  _events: { end: [Function: onReadableStreamEnd] },
  _eventsCount: 1,
  _maxListeners: undefined,
  _writableState:
   WritableState {
     objectMode: false,
     highWaterMark: 16384,
     finalCalled: false,
     needDrain: false,
     ending: false,
     ended: false,
     finished: false,
     destroyed: false,
     decodeStrings: false,
     defaultEncoding: 'utf8',
     length: 0,
     writing: false,
     corked: 0,
     sync: true,
     bufferProcessing: false,
     onwrite: [Function: bound onwrite],
     writecb: null,
     writelen: 0,
     bufferedRequest: null,
     lastBufferedRequest: null,
     pendingcb: 0,
     prefinished: false,
     errorEmitted: false,
     emitClose: false,
     bufferedRequestCount: 0,
     corkedRequestsFree:
      { next: null,
        entry: null,
        finish: [Function: bound onCorkedFinish] } },
  writable: true,
  allowHalfOpen: false,
  _sockname: null,
  _pendingData: null,
  _pendingEncoding: '',
  server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 7,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  _server:
   Server {
     _events:
      { connection: [Function],
        listening: [Function],
        error: [Function] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _connections: 7,
     _handle:
      TCP {
        reading: false,
        onread: null,
        onconnection: [Function: onconnection],
        [Symbol(owner)]: [Circular] },
     _usingWorkers: false,
     _workers: [],
     _unref: false,
     allowHalfOpen: false,
     pauseOnConnect: false,
     _connectionKey: '4:127.0.0.1:1883',
     [Symbol(asyncId)]: 963 },
  [Symbol(asyncId)]: 1115,
  [Symbol(lastWriteQueueSize)]: 0,
  [Symbol(timeout)]: null,
  [Symbol(kBytesRead)]: 0,
  [Symbol(kBytesWritten)]: 0 }

aedes.on says TypeError: aedes.on is not a function. I'm trying to add:

aedes.on('connectionError', function (client, err) {
  console.log('client error', client, err.message, err.stack)
})

aedes.on('publish', function (packet, client) {
  if (client) {
    console.log('message from client', client.id)
  }
})

aedes.on('subscribe', function (subscriptions, client) {
  if (client) {
    console.log('subscribe from client', subscriptions, client.id)
  }
})

aedes.on('client', function (client) {
  console.log('new client', client.id)
})

**Comment by nospam2k** [comment]
Ugh, very painful lesson. Must use:
 var aedes = global.get('aedes')();

vs.
 var aedes = global.get('aedes');

All about the parenthesis at the end!
