### ISSUE TITLE
server side common situation 4 mqtt

### ISSUE THREAD

**Issue by xushunke** [mcollina/aedes#223]
considering the server side, is there any way 2 make aedes work like this? or i need 2 implement this by myself?
![_15465326837023](https://user-images.githubusercontent.com/8627326/50649186-3048fe80-0fb8-11e9-9085-23c0f94b18d5.png)
![_15465326899493](https://user-images.githubusercontent.com/8627326/50649190-3343ef00-0fb8-11e9-9fac-92caa435b3ee.png)

**Comment by xushunke** [comment]
i mean the second one

**Comment by mcollina** [comment]
You'll need to implement this by yourself, as that behavior is not part of MQTT 3.1.1. It's part of the MQTT 5 spec, which Aedes do not implement.

**Comment by xushunke** [comment]
i am looking 4 a way 2 implement this feature,but nothing elegant found.can u give me a direction? pls.@mcollina
