### ISSUE TITLE
MongoDB Persistence

### ISSUE THREAD

**Issue by guptaashishiitr** [mcollina/aedes#23]
@mcollina : We are using mongodb for persistence with mosca and want to use the same with aedes as well. Do you know when can we have that?

**Comment by rushidesai** [comment]
Watch this project: https://github.com/mcollina/aedes-persistence-mongodb

**Comment by guptaashishiitr** [comment]
Any updates? Also a quick question does qos 2 make sense without db persistence?
How are offline messages handled?

**Comment by mcollina** [comment]
@guptaashishiitr 1) not really, it's done when it's done. Lot's of refactoring. 2) qos 2 makes almost no sense, but you can use redis or level 3) yes.

**Comment by guptaashishiitr** [comment]
Thanks a lot @mcollina  
We will use in mem to test and then move to redis
