### ISSUE TITLE
Possible bug on conn.destroySoon() vs. conn.destroy() in lib/client.js

### ISSUE THREAD

**Issue by mbrukman** [mcollina/aedes#231]
In [`lib/client.js`][lib-client-js], we see the following block of code:

```js
    if (conn.destroySoon) {
      conn.destroySoon()
    } if (conn.destroy) {
      conn.destroy()
    } else {
      conn.end()
    }
```

which is confusing, because the second `if` statement is in a position where it should be `else if` but it's written as a straight `if`, so it's possible that the object can call both `conn.destroySoon()` as well as `conn.destroy()`, and they're not mutually exclusive.

It seems that only one of those should be true, and they're mutually exclusive:

1. The second `if` should be `else if` (it appears that this was the intent)
1. The second `if` should be on a new line so that it's visually clear and obvious that it's orthogonal to the `if` statement above. Ideally, they would be separated by a blank line, possibly with a comment, as to why these cases are considered orthogonal to the above.

[lib-client-js]: https://github.com/mcollina/aedes/blob/bcaf919809c894383f4600d9c13f3f555b776c21/lib/client.js#L283-L289

**Comment by mcollina** [comment]
Likely! How did you spot this?

**Comment by mbrukman** [comment]
> How did you spot this?

Just browsing through the code, and noticed this as being slightly strange/unexpected.

**Comment by gnought** [comment]
This has been fixed in https://github.com/mcollina/aedes/commit/0bc8601946a44521914b1cf97fc0483b65d1336a
