### ISSUE TITLE
subsbribe to '+'

### ISSUE THREAD

**Issue by kaido42** [mcollina/aedes#235]
I expected to receive only one-level topics when subscribing to '+'. 
Seems to be working this way with mosquitto.

However, with aedes I'm receiving messages only from *two-level* topics, ie in format 'foo/bar', but not from single-level topics like 'foo' .. 

Do I understand the meaning of + topic incorrectly, or is there a bug somewhere?

**Comment by kaido42** [comment]
there seems to be something else wrong with + matching

when subscribing to topic '/+/kala/kala/kala', I receive messages from topics like 'foo/bar' .. how come?

**Comment by GavinDmello** [comment]
@kaido42 Can you add a script to reproduce the issue ?

**Comment by kaido42** [comment]
It seems I'm barking under the wrong tree here. Looks like the actual culprit is aedes-persistence-nedb

broker:
```
const Aedes = require('aedes')
const NedbPersistence = require('aedes-persistence-nedb')
const FsExtra = require('fs-extra')

const dataDir = './data'

FsExtra.emptyDirSync(dataDir)

var db = new NedbPersistence({
  path: dataDir,
  prefix: 'mqtt',
});

let aedes = Aedes({
	persistence: db
})

aedes.subscribe ('t/+/s', 
	function(packet, cb) {
		console.log ('got packet from', packet.topic)
		cb()
	},
	function(){

		packet = {	
		  cmd: 'publish',
		  topic: 'foo/bat/x',
		  // topic: 'foo/bar/x',
		  payload: 'payload',
		  retain: true	
		}
		aedes.publish (packet, function () {
			console.log ('published');
		})	

	})

var server = require('net').createServer(aedes.handle)
var port = 1883

server.listen(port, function () {
  console.log('server listening on port', port)
})
```

client:
```
const mqtt = require ('mqtt')

const conn_options = {
    clientId: "test1",
    username: "name",
    password: "pw",
    resubscribe: false,
    clean: true
}

const url = 'mqtt://localhost:1883'

let client = mqtt.connect(url, conn_options)

client.on("connect", function () {
	console.log ('connected:', client.connected)
})

client.on('message', function (topic, message, packet) {
	console.log ('message to topic:', topic)
})

client.subscribe('t/+/s')

client.publish('foo/bat/y', "test", { retain: true })
client.publish('foo/bat/y', "test", { retain: true })
```


start the broker

start the client. 

the client outputs messages from topics it's not subscribed to:

```
D:\node>node client.js
connected: true
message to topic: foo/bat/x
message to topic: foo/bat/y
```

replacing aedes-persistence-nedb with in-memory aedes-persistence fixes those problems .. 

should be closed. sorry.
