### ISSUE TITLE
kafka mqemitter

### ISSUE THREAD

**Issue by grath10** [mcollina/aedes#241]
Hello, I'd like to know if there's a kafka mqemitter available for aedes. If not, what should I do to realize this functionality. Any detailed suggestion or advice for reference is appreciated.  

PS: As for Mosca, there's a kafka backend demo, and herein, aedes also needs this if we want to migrate from mosca to aedes.

**Comment by mcollina** [comment]
Would you like to write one? I think you should look into https://github.com/mcollina/mqemitter-redis and follow the same project structure.

**Comment by grath10** [comment]
First, thx for your prompt reply. Taken your suggestion, I've looked into _mqemitter-redis_ and _mqemitter-mongodb_, but I'm confused at their different implementations.  
What should be taken into consideration if I'm going to write mqemitter-kafka. Here, I find [one](https://github.com/uwburn/mqemitter-kafka), but I'm not sure whether this is a fit or not. 
Any suggestions will be appreciated, thx again for sparing your priceless time!

**Comment by mcollina** [comment]
I don’t know, you’d have to test if it fits your requirements.

Il giorno sab 12 ott 2019 alle 04:20 June <notifications@github.com> ha
scritto:
