### ISSUE TITLE
heartbeat topic is in publish event

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#244]
Caught `'$SYS/' + that.id + '/heartbeat'` topic on `publish` event, is it a design?

the packet is as follows when `client` is null:
```
 message from client  null Packet {
  cmd: 'publish',
  brokerId: 'tHMNcxXrm',
  brokerCounter: 1,
  topic: '$SYS/tHMNcxXrm/heartbeat',
  payload: <Buffer 74 48 4d 4e 63 78 58 72 6d>,
  qos: 0,
  retain: false,
  messageId: 0 }
```

Seems related to https://github.com/mcollina/aedes/issues/7 and https://github.com/mcollina/aedes/commit/9bca79c9572774f332435fbc391d7932f39b2ae7, but they do not mention what the packet is when `client` is null on publish event.

If it is not a design, I could submit a PR not to publish the heartbeat on the publish event.

**Comment by gnought** [comment]
Seems related to https://github.com/mcollina/aedes/issues/7 and https://github.com/mcollina/aedes/commit/9bca79c9572774f332435fbc391d7932f39b2ae7, but they do not mention what the packet is when `client` is null on publish event.

**Comment by mcollina** [comment]
This is by design. It's a published packet, so it ends up in the `publish` event. `client` is `null`, because there is no client. It would be fantastic if you could update the docs.

**Comment by gnought** [comment]
Update README.me in PR https://github.com/mcollina/aedes/pull/245
