### ISSUE TITLE
Multiple clients subscribe same topic, no subscribers will receive message if one of them is closed by destroying socket

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#246]
I have written a unit test for testing this behaviour. https://github.com/gnought/aedes/commit/81a12299ce60fdca82f4068e5cfb71f6f31490fe

This always fails in Nodejs v10. https://travis-ci.org/gnought/aedes/builds/553241364

I don't know if it is a nodejs bug, but it will pass if we modified mqemitter https://github.com/mcollina/mqemitter/blob/master/mqemitter.js#L88-L92 as

```
  setImmediate(() => {
    this._matcher.remove(topic, notify)
    if (done) {
      done()
    }
  })
```

@mcollina any clue from your expertise?

**Comment by mcollina** [comment]
I don't know, nor I have the time to debug this :(.

**Comment by gnought** [comment]
Fixed in https://github.com/mcollina/aedes/pull/283
