### ISSUE TITLE
Why puback come first?

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#249]
In https://github.com/mcollina/aedes/blob/master/test/qos1.js#L677 unit test,

https://github.com/mcollina/aedes/blob/master/test/qos1.js#L714 subscribe packet come first and then the publish packet in the stream, why we expect puback is the first response?

I think it should be suback. @mcollina agree?

**Comment by mcollina** [comment]
We expect puback because registering a QoS 1 subscription is not an atomic operation: we are not pausing the reception of packets while we are storing the subscribe.
It's essentially an (important) implementation detail, but have very few practical implications.

**Comment by gnought** [comment]
Based on the unit test, let simplify as follows:
```
test.only('check stream', function (t) {
  var broker = aedes()
  var s = connect(setup(broker))

  console.log('check')
  s.outStream.on('data', function (packet) {
    console.log('stream',packet)
  })

  s.inStream.write({
    cmd: 'subscribe',
    messageId: 24,
    subscriptions: [{
      topic: 'hello',
      qos: 1
    }]
  })
  s.inStream.write({
    cmd: 'publish',
    topic: 'hello',
    payload: 'world',
    qos: 1,
    messageId: 42
  })
  setTimeout(() => { t.end() }, 200)
})
```
the sequence of getting responses after all InStream.write() calls are
1. `puback`
2. `publish`
3. `suback`

I agree we are not pausing any operations, but apparently this sequence is wrong.
We emit `suback` in completeSubscribe https://github.com/mcollina/aedes/blob/master/lib/handlers/subscribe.js#L31. Then aedes receives publish event and triggers to write `puback` https://github.com/mcollina/aedes/blob/master/lib/handlers/publish.js#L48. After then message is published, emit `publish`

The PR https://github.com/mcollina/aedes/pull/247 has corrected the sequence as
1. `suback`
2. `publish`
3. `puback`

**Comment by gnought** [comment]
In general, `puback` should be emitted after `publish`.

The simplified test result may result as 
1. `publish` -> `suback` -> `puback`.
2. `publish` -> `puback` -> `suback`

They should be still valid
