### ISSUE TITLE
Latest commit 0.12.4 issue

### ISSUE THREAD

**Issue by guptaashishiitr** [mcollina/aedes#25]
Hi
I am getting client disconnect errors quite frequently now

1452602353596 INFO new client andr_3e619e2221571966
1452602353597 INFO message published from broker to $SYS/EkYCGyCDl/new/clients 0
1452602353841 INFO Subscription Package:
{"topic":"user/10204470020541040/trip/5694f3e7c6fbf8144fd4c654/riderequests","qos":2}
1452602353841 INFO Client: andr_3e619e2221571966, Topic: user/10204470020541040/trip/5694f3e7c6fbf8144fd4c654/riderequests, Method: authorizeSubscribe; Entering function
1452602354419 INFO Client: andr_3e619e2221571966, Topic: user/10204470020541040/trip/5694f3e7c6fbf8144fd4c654/riderequests, Method: authorizeSubscribe; Subscription successful
1452602356190 INFO message published from broker to $SYS/EkYCGyCDl/heartbeat 0
1452602378812 INFO Client disconnected - andr_3e619e2221571966

**Comment by mcollina** [comment]
It's really hard to help. Please provide steps to reproduce.

**Comment by guptaashishiitr** [comment]
Found issue with mqtt client. Sorry for the trouble,
