### ISSUE TITLE
PubRec should not be the first packet in QoS 2

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#250]
An unit test
```
test.only('check stream', function (t) {
  var broker = aedes()
  var s = connect(setup(broker))

  console.log('check')
  s.outStream.on('data', function (packet) {
    console.log('stream',packet)
    if (packet.cmd === 'pubrec') {
      s.inStream.write({
        cmd: 'pubrel',
        messageId: packet.messageId
      })
    }
  })

  s.inStream.write({
    cmd: 'subscribe',
    messageId: 24,
    subscriptions: [{
      topic: 'hello',
      qos: 2
    }]
  })
  s.inStream.write({
    cmd: 'publish',
    topic: 'hello',
    payload: 'world',
    qos: 2,
    messageId: 42
  })
  setTimeout(() => { t.end() }, 200)
})
```

The sequence of received stream will be:
`pubrec` -> `suback` -> `publish` -> `pubcomp`

It seems it violates the spec stated in http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718048, `pubrec` should be after `publish` and before `pubcomp`

Why we trigger the publish after receiving `pubrel` in https://github.com/mcollina/aedes/blob/master/lib/handlers/pubrel.js#L38 ?

**Comment by gnought** [comment]
Make the publish (https://github.com/mcollina/aedes/blob/master/test/qos2.js#L11) and receive (https://github.com/mcollina/aedes/blob/master/test/qos2.js#L48) functions be more verbose as follows (added console.log):
```
function publish (t, s, packet, done) {
  var msgId = packet.messageId

  s.inStream.write(packet)

  s.outStream.once('data', function (packet) {
    console.log('data | pub 1', packet.cmd)
    t.deepEqual(packet, {
      cmd: 'pubrec',
      messageId: msgId,
      length: 2,
      dup: false,
      retain: false,
      qos: 0
    }, 'pubrec must match')

    s.inStream.write({
      cmd: 'pubrel',
      messageId: msgId
    })

    s.outStream.once('data', function (packet) {
      console.log('data | pub 2', packet.cmd)
      t.deepEqual(packet, {
        cmd: 'pubcomp',
        messageId: msgId,
        length: 2,
        dup: false,
        retain: false,
        qos: 0
      }, 'pubcomp must match')

      if (done) {
        done()
      }
    })
  })
}

function receive (t, subscriber, expected, done) {
  subscriber.outStream.once('data', function (packet) {
    console.log('data | receive 1', packet.cmd)
    t.notEqual(packet.messageId, expected.messageId, 'messageId must differ')

    var msgId = packet.messageId
    delete packet.messageId
    delete expected.messageId
    t.deepEqual(packet, expected, 'packet must match')

    subscriber.inStream.write({
      cmd: 'pubrec',
      messageId: msgId
    })

    subscriber.outStream.once('data', function (packet) {
      console.log('data | receive 2', packet.cmd)
      subscriber.inStream.write({
        cmd: 'pubcomp',
        messageId: msgId
      })
      t.deepEqual(packet, {
        cmd: 'pubrel',
        messageId: msgId,
        length: 2,
        qos: 1,
        retain: false,
        dup: false
      }, 'pubrel must match')

      done()
    })
  })
}
```

In unit test 'publish after disconnection' https://github.com/mcollina/aedes/blob/master/test/qos2.js#L377, we will get the following sequence:
```
data | pub 1 pubrec
data | receive 1 publish
data | pub 2 pubcomp
data | receive 2 pubrel
data | pub 1 pubrec
data | pub 2 pubcomp
```

Apparently it's in wrong order. May I know what the order sequence should be expected in the unit test in your first thought? @mcollina

**Comment by mcollina** [comment]
A long amount of time has passed, and I do not remember. This is the same type of transactional behavior that MQTT does not really specify, and it’s up for the broker to implement.

**Comment by gnought** [comment]
From the MQTT 3.11 spec, the transactional behaviour in QoS 2 is defined.
1. `publish`
2. `pubrec `
3. `pubrel`
4. `pubcomp`

Likely the test tries to demonstrate the publisher still send `pubrec` after the subscriber disconnects. In this case, `pubrel` shouldn't be sent and `pubcomp` won't be there.
The whole unit test is needed to rewrite. @mcollina could I?

**Comment by mcollina** [comment]
It's hard for me to follow up on these long issues at this point. Feel free to send a PR that address your concerns, motivate it with reference to the spec, and I'll review when I have more time.
