### ISSUE TITLE
Drop nodejs 6 support

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#263]
Should we drop nodejs 6 support?
https://github.com/mcollina/aedes/blob/master/.travis.yml#L3

**Comment by mcollina** [comment]
yes

Il giorno mar 16 lug 2019 alle 14:20 Gnought <notifications@github.com> ha
scritto:

**Comment by gnought** [comment]
Refer to https://github.com/mcollina/aedes/pull/266
