### ISSUE TITLE
Retry mechanism in Aedes Broker -> Subscriber (QoS 2)

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#271]
MQTT QoS 2 flow: https://emqx-enterprise-docs-en.readthedocs.io/en/latest/_images/mqtt_3.png (Typo: PUBACK should be PUBREC)

**PUBLISHER -> Aedes Broker (QoS 2)**
- Aedes stores message when it receives PUBLISH https://github.com/mcollina/aedes/blob/master/lib/handlers/publish.js#L45
- Aedes acknowledges back PUBREC to the publisher
- Aedes receives PUBREL from the publisher and push messages to subscribers. After that it will delete the stored message
https://github.com/mcollina/aedes/blob/master/lib/handlers/pubrel.js#L47

This make senses that when the publisher resends PUBREL, Aedes will re-send PUBCOMP and won't push message again to subscribers.

**Aedes Broker -> Subscriber (QoS 2)**
- Normally Aedes will publish messages to subscribers.
Case 1: If broker does not receive PUBREC, it seems aedes do not have a retry mechanism to re-publish again.
Case 2: If broker does not receive PUBCOMP, it seems aedes does not have a retry mechanism to re-send PUBREL again.
- Even if there is a retry mechanism for Case 1, we cannot resend PUBLISH again as it has been deleted in receiving PUBREL phrase.

**Comment by mcollina** [comment]
I don't understand what the issue is.

**Comment by gnought** [comment]
Aedes should keep trying to send PUBLISH/PUBREL if it does not receive PUBREC/PUBCOMP responses from subscribers within a period of time, otherwise persistence storage will accumulate many outstanding messages.

**Comment by mcollina** [comment]
that’s not part of the MQTT spec

Il giorno mer 31 lug 2019 alle 13:39 Gnought <notifications@github.com> ha
scritto:

**Comment by gnought** [comment]
I think there is. http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718037
> The DUP flag MUST be set to 1 by the Client or Server when it attempts to re-deliver a PUBLISH Packet [MQTT-3.3.1.-1]

We need to toggle DUP flag when aedes resend messages to subscribers.

**Comment by gnought** [comment]
and I think this diagram http://www.steves-internet-guide.com/wp-content/uploads/mqtt-publish-flow-qos-2.jpg should apply

**Comment by mcollina** [comment]
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718103 says that

> When a Client reconnects with CleanSession set to 0, both the Client and Server MUST re-send any unacknowledged PUBLISH Packets (where QoS > 0) and PUBREL Packets using their original Packet Identifiers [MQTT-4.4.0-1]. This is the only circumstance where a Client or Server is REQUIRED to redeliver messages.

So, no, we should not resend messages on an open connection.

**Comment by gnought** [comment]
That's the case that when subscribers **reconnect** and server need to redeliver messages.

How about the case that aedes has sent a PUBLISH message to subscribers, but there's packet loss in the connection? Those subscribers will remain silence, they will not know what's going and even they need to reconnect to get all messages.

**Comment by mcollina** [comment]
packet loss is managed by TCP.

Il giorno mer 31 lug 2019 alle ore 17:36 Gnought <notifications@github.com>
ha scritto:

**Comment by gnought** [comment]
It sounds right.

How about there is a case that a subscriber intentionally does not response back only PUBREC/PUBCOMP, maybe he is a hacker, will he screw up the aedes and even persistence storage?

**Comment by mcollina** [comment]
Then resending is only going to make things worse and clog the network.
That is a valid case, but the normal thing should be to "drop" messages
that have not been ack'ed after a while (configurable) - with a TTL.

Il giorno mer 31 lug 2019 alle ore 18:45 Gnought <notifications@github.com>
ha scritto:

**Comment by gnought** [comment]
Should it be implemented in persistence side or aedes side?

**Comment by mcollina** [comment]
IMHO it's persistence specific (Redis, Mongo, etc).

Il giorno mer 31 lug 2019 alle ore 18:51 Gnought <notifications@github.com>
ha scritto:
