### ISSUE TITLE
Cannot read property 'charCodeAt' of undefined on publish by client

### ISSUE THREAD

**Issue by ayushsharma82** [mcollina/aedes#274]
Hi,
I am using Aedes MQTT Broker in one of my projects. Thanks for this wonderful mqtt broker on nodejs!

### Problem:

There is a `aedes.subscribe('+/firmware/report')` wildcard topic subscription on Aedes MQTT broker.

Upon publish by a client on that topic, a typeerror occures:
```
(node:22772) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'charCodeAt' of undefined
    at isWildcardThatMatchesSys (\node_modules\aedes\lib\handlers\subscribe.js:131:20)
```

I'm not sure why this is happening.. Any help / debbuging would be appriciated.

**Comment by gnought** [comment]
`var aedes = require('aedes')()` ?

**Comment by ayushsharma82** [comment]
I have that on top of my code.

**Comment by gnought** [comment]
May we know which aedes version you are using, and could provide a pure javascript code to reproduce it?

**Comment by ayushsharma82** [comment]
Yup. I will provide you a example in couple of minutes.. I am using authorize subscribe too..

**Comment by ayushsharma82** [comment]
So here is an example that reproduces the error:

### Observation:

From what I have observed, The `TypeError: Cannot read property 'charCodeAt' of undefined` Error occurs when using aedes with `authorizeSubscribe`  function. When this line of code: `done(null, sub.topic === 'foo/firmware/status')`  returns true in `authorizeSubscribe` function, the error pops up.


### Example ( to reproduce error ): 

#### Broker: 

```
const aedes = require('aedes')()
const server = require('net').createServer(aedes.handle)

// Auth
aedes.authenticate = async (client, username, password, done) => {
    if(username === 'foo' && password.toString() === 'bar'){
        client.username = username;
        done(null, true);
    }else{
        done(null, false);
    }
}

aedes.authorizeSubscribe = (client, sub, done) => {
    return done(null, sub.topic === 'foo/firmware/status');
}

aedes.authorizePublish = (client, pub, done) => {
    return done(null, pub.topic === 'foo/firmware/eureka');
}


// Events
aedes.on('client', async (client) => {
    try{
        console.log('Client #'+client.username+' connected.');
    }catch(err){
        console.error(err);
    }
});

aedes.on('clientDisconnect', async (client) => {
    try{
        console.log('Client #'+client.username+' disconnected.');
    }catch(err){
        console.error(err);
    }
});

aedes.on('subscribe', (subscriptions, client) => {
    if(client != null){
        let topics = subscriptions.map((pack) => pack.topic);
        topics = topics.join();
        console.log('Client #'+client.username+' subscribed to '+topics);
    }
});

aedes.on('publish', (packet, client) => {
    if(client != null){
        console.log('Client #'+client.username+' published to '+packet.topic);
    }
});

aedes.subscribe('+/firmware/eureka', function (packet, cb) {
    console.log(packet)
    return cb();
})

// Start MQTT Server
server.listen(1883, '0.0.0.0',() => {
    console.log('MQTT Broker listening on port:', 1883);
})
```

#### Client
```
var mqtt = require('mqtt')

var client  = mqtt.connect({
    host: '192.168.1.72',
    port: 1883,
    username: "foo",
    password: "bar"
})
 

client.on('connect', function () {
  client.subscribe('foo/firmware/status', function (err) {
    if (!err) {
      client.publish('foo/firmware/eureka', "Hello! This is a test message.");
    }
  })
})
 
client.on('message', function (topic, message) {
  // message is Buffer
  console.log(message.toString())
  client.end()
})
```

**Comment by ayushsharma82** [comment]
@gnought  I am using the latest version of aedes ( v0.39.0 ).

**Comment by gnought** [comment]
Thanks for the code. I could reproduce it by issuing `mosquitto_sub -t foo/firmware/status -u foo -P bar`. Let see what we could find. :)

**Comment by gnought** [comment]
Basically this error comes from `return done(null, sub.topic === 'foo/firmware/status')`.

The 2nd parameter in `done()` should be `sub`. It should be an object `{ topic: 'foo/firmware/status', qos: 0 }` in your case. Your code change the 2nd parameter, and internally aedes will think `sub` structure to a boolean, that is the reason why `charCodeAt` property not found.

I suggest to change the `authorizeSubscribe` as
```
aedes.authorizeSubscribe = (client, sub, done) => {
  if (sub.topic !== 'foo/firmware/status') {
    return done(new Error('not allowed'))
  }
  done(null, sub)
}
```

You many think it is weird why we need to pass incoming `sub` parameter to `done()`. This is the magic of aedes to get its flow right. 

A bonus: you could change the `sub.topic` to treat subscribers to subscribe other topic, like
```
aedes.authorizeSubscribe = (client, sub, done) => {
  sub.topic = 'foo/firmware/status'
  done(null, sub)
}
```
then all subscribers will subscribe `foo/firmware/status`, no matter what he specifies e.g. `mosquitto_sub -t foo/firmware/fake -u foo -P bar`

**Comment by gnought** [comment]
If you feel good, please close this issue. :)

**Comment by ayushsharma82** [comment]
Oh, Awesome! I was following the `mosca` style. Haha
I will do the needful changes in my code. Thanks a lot @gnought !
