### ISSUE TITLE
Drop safe-buffer

### ISSUE THREAD

**Issue by mcollina** [mcollina/aedes#276]
Given we have dropped support for Node 6, we can also remove safe-buffer

**Comment by gnought** [comment]
Could it be done after merging https://github.com/mcollina/aedes/pull/264 ?

**Comment by mcollina** [comment]
yes no problem

Il giorno sab 20 lug 2019 alle 07:33 Gnought <notifications@github.com> ha
scritto:

**Comment by gnought** [comment]
This refers to PR https://github.com/mcollina/aedes/pull/296
