### ISSUE TITLE
clientDisconnect emited twice

### ISSUE THREAD

**Issue by litbak** [mcollina/aedes#28]
when a client disconnects abnormally without a disconnect message, the clientDisconnect event emited twice, which also infulence connected client count. 

aedes.on('clientDisconnect', function(client) {
    console.log('Client Disconnected: ' + client.id + ' total: ' + aedes.connectedClients);
});

**Comment by mcollina** [comment]
this should be easy to fix, would you mind sending a PR?

**Comment by mcollina** [comment]
I've tried hard to reproduce this, and I couldn't.
Can you please add steps to reproduce?

Closing for now
