### ISSUE TITLE
Duplicate PUBLISH packets in directly push to a QoS 2 client.

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#281]
It seems that we get a serious bug.

When we direct push a PUBLISH to a QoS 2 client, we get duplicate publish packets. The following test is trying to demonstrate it. The `publishCount` is 2, and `nonPublishCount` is 1.
However the correct result should be `publishCount` is 1, and `nonPublishCount` is 1.

Test code:
```
test('publish direct to a single client QoS 2', function (t) {
  var broker = aedes()
  var messageId
  var clientId
  var publishCount = 0
  var nonPublishCount = 0

  broker.on('client', function (client) {
    clientId = client.id
    client.publish({
      topic: 'hello',
      payload: Buffer.from('world'),
      qos: 2
    }, function (err) {
      t.error(err, 'no error')
    })
  })

  var s = connect(setup(broker))

  s.outStream.on('data', function (packet) {
    if (packet.cmd === 'publish') {
      publishCount++
      console.log('s.outStream', packet)
      s.inStream.write({
        cmd: 'pubrec',
        messageId: packet.messageId
      })
    } else {
      nonPublishCount++
      messageId = packet.messageId
      s.inStream.write({
        cmd: 'pubcomp',
        messageId: packet.messageId
      })
    }
  })

  broker.on('closed', function () {
    console.log(publishCount)
    console.log(nonPublishCount)
  })
})
```

**Comment by mcollina** [comment]
Is this against master or against the last published version? In other terms, is this the result of some of the changes to persistence? Would you mind sending a PR to fix?

**Comment by gnought** [comment]
The test is based on the `master` branch with v6.0.0 persistence.

It seems that I find the root clause.
The publish packet is QoS 2 and will sit in offline queue until broker receives pubcomp.
The connect actions are 
```
var connectActions = [
  authenticate,
  fetchSubs,
  restoreSubs,
  storeWill,
  registerClient,
  doConnack,
  emptyQueue
]
```

1. `client` event is emitted when in `registerClient` action.
2. publish packet is then triggered to push it into the stream.
3. After some times, `emptyQueue` run and push the publish packet in offline queue again.

It makes sense that `client` event is raised when a new client connects, but it is too earlier for the test.
Similarly 2 tests also depends on `client` event.
https://github.com/mcollina/aedes/blob/master/test/client-pub-sub.js#L24
https://github.com/mcollina/aedes/blob/master/test/client-pub-sub.js#L55

Should we create another new event like `clientReady` ?

**Comment by mcollina** [comment]
Yes, adding the clientReady event would be good. When will it be fired?
