### ISSUE TITLE
backpressure support in server.publish

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#29]
`server.publish` is mentioned to be backpressure supported. 
Can you elaborate on this @mcollina ?

**Comment by mcollina** [comment]
Possibly it's not correctly phrased. In the in-memory implementation https://github.com/mcollina/mqemitter, the callback is called when the message has been sent to delivery to each subscribing client. In other implementations, it is called when the message has been sent to the upstream pubsub broker.

It would be great if you could send a PR to the README, maybe wording all of this a little better.
