### ISSUE TITLE
Do not restore QoS 0 subscriptions when clean=false

### ISSUE THREAD

**Issue by gnought** [mcollina/aedes#299]
Based on MQTT spec,
> After the disconnection of a Session that had CleanSession set to 0, the Server MUST store further QoS 1 and QoS 2 messages that match any subscriptions that the client had at the time of disconnection as part of the Session state [MQTT-3.1.2-5]

In this test "_restore QoS 0 subscriptions not clean_"
https://github.com/mcollina/aedes/blob/master/test/basic.js#L472

This is totally wrong.

**Comment by mcollina** [comment]
That paragraph does not relate to that test. It does not check about QoS delivery, but rather on the fact that QoS 0 subscriptions must be restored.

**Comment by gnought** [comment]
I tried a test in vernemq.

In QoS 0 publish:
1. Client A subscribes with clean=false. `mosquitto_sub -t hello -c -i my-client-0 -q 0`
2. Client A disconnects
3. Client B publishes message `mosquitto_pub -t hello -m world -q 0`
4. Client A reconnects, same command in (1)

Client A does not receive any messages.

In QoS 1 publish:
1. Client A subscribes with clean=false. `mosquitto_sub -t hello -c -i my-client-0 -q 0`
2. Client A disconnects
3. Client B publishes message `mosquitto_pub -t hello -m world -q 1`
4. Client A reconnects, same command in (1)

Client A still does not receive any messages.

**Comment by gnought** [comment]
I have checked with the table http://www.steves-internet-guide.com/wp-content/uploads/MQTT-qos-retain-clean-session-table.jpg in http://www.steves-internet-guide.com/mqtt-clean-sessions-example/

**Comment by mcollina** [comment]
Section 3.1.2.4 describes this behavior.
All subscriptions must be restored. A server may store the QoS 0 messages in between or not.

As far as I recall, mosquitto implements this logic.

**Comment by gnought** [comment]
Tried in mosquitto server,
QoS 0 subscriptions won't be restored, behaviour as same as in vernemq.

**Comment by gnought** [comment]
In [MQTT-3.1.2-5], it said the server stores further QoS 1 and 2 messages that **MATCH** the any subscriptions that the client had at the time of disconnection.

If the client subscribes QoS 0 and disconnects, server should not store any QoS 1 and 2 messages for him, because the QoS 1 and 2 messages do not match to the QoS what he subscribed at the time of disconnection.

Agree?

**Comment by mcollina** [comment]
Yes, storing the message is a bug. But the subscription must be restored, i.e. when the client reconnects any _new_ messages must be delivered. This is what I mean by “restore” the subscriptions.

**Comment by gnought** [comment]
The following is a unit test, and test on mosquitto and vernemq.
1. client connects and subscribes qos 0 `hello` topic with clean=false, then disconnect.
2. pubClient publishes `world` msg to `hello` topic with qos 0, then disconnects
3. client reconnects, if server restores its qos 0 subscription, client should receives the `world` msg, but it is not the case.

```
'use strict'

var mqtt = require('mqtt')
var test = require('tape')

function connect () {
  return mqtt.connect('mqtt://localhost', { clientId: 'abc', clean: false })
}

test('restore QoS 0 subscription', function (t) {
  var client = connect()
  client.on('connect', function () {
    client.subscribe({ hello: { qos: 0 } }, function (_, granted) {
      // client subscribes hello, qos: 0, and disconnects
      client.end()
      var pubClient = connect()
      // pubClient publishes hello, qos: 0, and disconnects
      pubClient.publish('hello', 'world', { qos: 0 }, function () {
        pubClient.end()
        // client reconnects
        client = connect()
        client.on('message', function (topic, message) {
          console.log('message received: ', message.toString())
          client.end()
          t.end()
        })
      })
    })
  })
})
```

**Comment by gnought** [comment]
If we change the QoS to 1 (`qos_value =1`), client will receives `world` message.

**Comment by mcollina** [comment]
We are not talking about the the same thing. You are talking about offline enqueueing, I’m talking about subscriptions. Try publishing the message _after_ reconnection.

**Comment by gnought** [comment]
ok, I modified the test code as below.
Same, client still not receive `world` message.

```
'use strict'

var mqtt = require('mqtt')
var test = require('tape')

var qosValue = 0

function connect () {
  return mqtt.connect('mqtt://localhost', { clientId: 'abc', clean: false })
}

test('restore QoS 0 subscription', function (t) {
  var client = connect()
  client.on('connect', function () {
    client.subscribe({ hello: { qos: qosValue } }, function (_, granted) {
      // client subscribes hello, qos: qosValue, and disconnects
      client.end()
      // client reconnects
      client = connect()
      var pubClient = connect()
      // pubClient publishes hello, qos: qosValue, and disconnects
      pubClient.publish('hello', 'world', { qos: qosValue }, function () {
        pubClient.end()
        client.on('message', function (topic, message) {
          console.log('message received: ', message.toString())
          client.end()
          t.end()
        })
      })
    })
  })
})
```

**Comment by mcollina** [comment]
Likely you need to wait the client being connected.

Il giorno mar 13 ago 2019 alle 20:56 Gnought <notifications@github.com> ha
scritto:

**Comment by gnought** [comment]
ok, I wrap it in to `connect` event, but the result is the same.

```
'use strict'

var mqtt = require('mqtt')
var test = require('tape')

var qosValue = 0

function connect () {
  return mqtt.connect('mqtt://localhost', { clientId: 'abc', clean: false })
}

test('restore QoS 0 subscription', function (t) {
  var client = connect()
  client.on('connect', function () {
    client.subscribe({ hello: { qos: qosValue } }, function (_, granted) {
      // client subscribes hello, qos: qosValue, and disconnects
      client.end()
      // client reconnects
      client = connect()
      client.on('connect', function () {
        var pubClient = connect()
        // pubClient publishes hello, qos: qosValue, and disconnects
        pubClient.publish('hello', 'world', { qos: qosValue }, function () {
          pubClient.end()
          client.on('message', function (topic, message) {
            console.log('message received: ', message.toString())
            client.end()
            t.end()
          })
        })
      })
    })
  })
})
```

**Comment by gnought** [comment]
ok, @mcollina you're right. The QoS 0 subscription will be restored when clean=false.

The client and pubClient are in same clientID. The restored QoS 0 subscription happens in pubClient.
The following test refines to use different clientID for pubClient. All goes fine. :)

```
'use strict'

var mqtt = require('mqtt')
var test = require('tape')

var qosValue = 0

function connect (clientId) {
  return mqtt.connect('mqtt://localhost', { clientId: clientId, clean: false })
}

test('restore QoS 0 subscription', function (t) {
  var client = connect('abc')
  client.on('connect', function () {
    client.subscribe({ hello: { qos: qosValue } }, function (_, granted) {
      // client subscribes hello, qos: qosValue, and disconnects
      client.end()
      // client reconnects
      client = connect('abc')
      client.on('connect', function () {
        var pubClient = connect('pub')
        pubClient.on('connect', function () {
          // pubClient publishes hello, qos: qosValue, and disconnects
          pubClient.publish('hello', 'world', { qos: qosValue }, function () {
            pubClient.end()
            client.on('message', function (topic, message) {
              console.log('message received: ', message.toString())
              client.end()
              t.end()
            })
          })
        })
      })
    })
  })
})
```

**Comment by gnought** [comment]
The above unit test is an alternative good test in this topic, i will add it in our test suite too. :)

**Comment by mcollina** [comment]
This was a good discussion!

Il giorno mar 13 ago 2019 alle 22:22 Gnought <notifications@github.com> ha
scritto:
