### ISSUE TITLE
General Information

### ISSUE THREAD

**Issue by Andreyooo** [mcollina/aedes#302]
Hello,
I´m a beginner with MQTT and I wanted to know if Aedes is ready to be used? It´s out for a long time, what confuses me though is that you can´t find anything about Aedes on the internet. 
Mosca doesn`t seem to get any support anymore, yet online there are no articles/blogs about Aedes.
It´s not listed here aswell [https://github.com/mqtt/mqtt.github.io/wiki/server-support](url)

Also does it support QoS 2 or does it have the same functions as mosca? Which MQTT versions does Aedes support?

**Comment by gnought** [comment]
Aedes is a successor of mosca. It is much more conform to mqtt spec v3.1 and v3.1.1, and supports QoS 2. Its storage layer, and emitter system is pluggable, and far more stable and extensible compared with mosca.

Using the aedes provided benchmark tools, i could get nearly 98k messages per second in my local i5 mac w/ 8gb ram.

You could test it using 0.39 release. We are going to release a new release if we are fast and have much more time.

It is best if you could report any issues.

The link you sent is useful, and we may need to notify the author to have a update on.

**Comment by Andreyooo** [comment]
Thank you for the quick reply 👍 .
Maybe update the wiki with a quick overview, as it was done for mosca if you got the time.
[https://github.com/mcollina/mosca/wiki](url)

Good luck developing
