### ISSUE TITLE
Any plan to migrate to Typescript?

### ISSUE THREAD

**Issue by moralesmx** [mcollina/aedes#304]
I'd love to work on that.

**Comment by mcollina** [comment]
Not right now, but we’ll be happy to have types.

Il giorno ven 23 ago 2019 alle 19:58 Luis Angel Morales Romo <
notifications@github.com> ha scritto:

**Comment by moralesmx** [comment]
ES6/ES2015?

**Comment by mcollina** [comment]
I have no plans to migrate this to introduce any transpiling layer, if this is what you are asking. One day Node will support “import” in all LTS line, and then we’ll migrate. This is at least 1-2 years ahead.

**Comment by moralesmx** [comment]
Thanks for your response!

**Comment by moralesmx** [comment]
BTW, Node.js v8 is on Maintenance LTS and it ends on 2019-12-31.
