### ISSUE TITLE
KeepAlive Timeouts

### ISSUE THREAD

**Issue by guptaashishiitr** [mcollina/aedes#31]
We have suddenly started getting keep alive timeouts suddenly.  It might be a client issue but can you check if latest commit caused anything

2016-02-12T06:06:17.805Z - error:  Error: keep alive timeout
    at keepaliveTimeout (/app/nodeApp/hopponnodejs/HopponSimulator/node_modules/aedes/lib/handlers/connect.js:43:28)
    at timerWrapper [as _onTimeout] (/app/nodeApp/hopponnodejs/HopponSimulator/node_modules/aedes/node_modules/retimer/retimer.js:21:16)
    at Timer.listOnTimeout [as ontimeout] (timers.js:121:15)
2016-02-12T06:06:17.805Z - error: client error andr_3bb73ec23c08b68c keep alive timeout
2016-02-12T06:06:17.805Z - info: Client disconnected -  andr_3bb73ec23c08b68c

**Comment by mcollina** [comment]
the tests are passing fine, so maybe it's a client issue. What are you using? how long is your keepalive?

**Comment by guptaashishiitr** [comment]
Paho Android service is what we are using and pinger class in that is scheduled to send it every 5 seconds.
Also connectTimeout is set to 3 min in aedes but still for some reason it just disconnects after 11-15 seconds. I have authorize publish method and I send console logs for every topic but I don't see keep alive topics there except for broker ones for clustering but none from client side. Let's say we are not getting client keep alive shouldn't it disconnect after 3 min anyways.

**Comment by mcollina** [comment]
What is the Android Service doing? Just sitting there and keeping the connection idle? Is it doing anything every 11-15 seconds?

There are no keep alive topics, but only PING and PINGRESP commands that are being sent as part of the wire protocol

**Comment by behrad** [comment]
> it just disconnects after 11-15 seconds

Are you sure android is not stopping your service, or it isn't cause of phone going to sleep or power saving mode?

**Comment by guptaashishiitr** [comment]
Issue was related to keepalive being set to a very low value. I will close
out the issue.

*Thanks & Regards*



*Ashish Gupta* | AVP |* JPMorgan Chase & Co.* | Cedar Knolls, NJ, USA
B.Tech. Electrical Engineering, IIT Rookee, Roorkee, India

Mobile : +1 973 234 0078

* ashish.xx.gupta@jpmchase.com <shikha.v.gupta@jpmorgan.com> |
www.jpmorgan.com
