### ISSUE TITLE
used ram memory

### ISSUE THREAD

**Issue by stefano055415** [mcollina/aedes#333]
Is it possible to reduce the use of RAM?

With about 20k connections the usage is 1.3gb

thanks

**Comment by mcollina** [comment]
By doing some simple math, we can estimate that each connection is using about 65 bytes. This is pretty low already, and I don’t think we can easily improve on it.
Il 7 nov 2019, 08:52 +0100, stefano055415 , ha scritto:

**Comment by stefano055415** [comment]
ok thanks

**Comment by mcollina** [comment]
I’ll be to take a PR in that sense, if you can figure out a way.
Il 7 nov 2019, 09:18 +0100, stefano055415 <notifications@github.com>, ha scritto:
