### ISSUE TITLE
Unable to attach a http server with aedes server , like mosca's attachHttpServer . Any workaround ?

### ISSUE THREAD

**Issue by debjeet-sarkar** [mcollina/aedes#38]

**Comment by mcollina** [comment]
This is not in the scope of this project, and it will be integrated with Mosca soon. You can achieve the same thing by using http://npm.im/websocket-stream.

**Comment by debjeet-sarkar** [comment]
I am sending my client side packet using mows.js and I am trying to pass the incoming stream to aedes using websocket-stream . Here is my code snippet 

`var http = require('http')
var websocket = require('websocket-stream')
var RedisPersistence = require('aedes-persistence-redis')()
var aedes = require('aedes')({
	concurrency: 1000,
	persistence : RedisPersistence
})

var httpServ = http.createServer()

var wss = websocket.createServer({server: httpServ},handle)
	
function handle(stream){
	stream.pipe(server)
}

var server = require('net').createServer(aedes.handle)
var port = 1884	


httpServ.listen(port, function (req,res) {
  console.log('server listening on port', port)
})`

**Comment by alliv8** [comment]
You have to bind aedes to wss, not a new tcp server.

```javascript
var http = require('http')
var websocket = require('websocket-stream')
var RedisPersistence = require('aedes-persistence-redis')()
var aedes = require('aedes')({
    concurrency: 1000,
    persistence : RedisPersistence
})

var httpServ = http.createServer()
var port = 1884

var wss = websocket.createServer({server: httpServ, port: port}, aedes.handle)

```

This should work

**Comment by mcollina** [comment]
@alliv8 explained it perfectly.

**Comment by debjeet-sarkar** [comment]
Got a clear idea , Thanks @alliv8  .
