### ISSUE TITLE
Replicating on multi core cpu

### ISSUE THREAD

**Issue by cristian-stoicescu** [mcollina/aedes#43]
I'm currently looking into using aedes for a web / mobile based chat platform.
However, due to node's limitation of using only 1 CPU core, I need to scale this at least to use all the cores. I tried to spawn the processes using redis persistence, but between clients, publishes were not shared.

Any tips ?

**Comment by mcollina** [comment]
You should also use https://github.com/mcollina/mqemitter-redis in the `mq` option.
