### ISSUE TITLE
does aedis can  be deploy distributed?

### ISSUE THREAD

**Issue by tianyayouxiaer** [mcollina/aedes#46]
1、aedes can  be deploy many instances by pm2 in one pc?
2、aedes can  be deploy on many pc distributed?
3、is needed bridges if deploy on many pc?

**Comment by mcollina** [comment]
1. aedes has currently no support for node cluster module, you will need to rely on the setup for 2.
2. yes, here is an example with redis: https://gist.github.com/mcollina/a37f135136192d9c58a4
3. no

**Comment by tianyayouxiaer** [comment]
I can open the link you give above,because I,m not in  US,the dist is blocked in our Country，could you give me a another link，thanks ！

**Comment by tianyayouxiaer** [comment]
dear：
I want use your project aedes in my work，because one machine can not meet the need（many clients），so I want use the method in the picture bottom，
1、I use redis as you tell me https://gist.github.com/mcollina/a37f135136192d9c58a4 
2、I use ngix to do the tcp proxy
3、I use three machin to run aedes
4、on every machin，I use pm2 to run 4 instance of aedes
5、in sum，there are 12 aedes instance in the system。

I don,t know this method is can be ok ?could you give me some advice?thaks very much!




2016-05-04 

hzlixiutang 



发件人：Matteo Collina <notifications@github.com>
发送时间：2016-05-03 14:26
主题：Re: [mcollina/aedes] does aedis can be deploy distributed? (#46)
收件人："mcollina/aedes"<aedes@noreply.github.com>
抄送："tianyayouxiaer"<hzlixiutang@163.com>,"Author"<author@noreply.github.com>

aedes has currently no support for node cluster module, you will need to rely on the setup for 2. 
yes, here is an example with redis: https://gist.github.com/mcollina/a37f135136192d9c58a4 
no

**Comment by mcollina** [comment]
use Haproxy instead of Nginx. You will need a Redis instance also.

**Comment by jyotman** [comment]
@mcollina Any specific reason to advice Haproxy over Nginx? Also considering in mind if one wants to setup SSL too, which would be better? Thanks!

**Comment by mcollina** [comment]
HAProxy is a TCP load balancer that can be HTTP-aware. NGINX is a web server that can load balance TCP. HAProxy is easier to configure for MQTT.

**Comment by cordovapolymer** [comment]
@mcollina 

> aedes has currently no support for node cluster module, you will need to rely on the setup for 2.

Does it mean that you can only run one aedes instance on single machine?

> yes, here is an example with redis: https://gist.github.com/mcollina/a37f135136192d9c58a4

So the idea is to have one redis server on main machine and one aedes instance per machine which all use that main redis server?

**Comment by GavinDmello** [comment]
@cordovapolymer  yes. 
I think you can also have different Aedes process' on different ports on the same server and then link them to your LB, depending the type of traffic you get

**Comment by mcollina** [comment]
It is currently possible to share a mqemitter with multiple processes with:
https://www.npmjs.com/package/mqemitter-child-process (yes, it works with cluster).

However the same capabilities were not developed for persistence (yet!).
