### ISSUE TITLE
cluster mode

### ISSUE THREAD

**Issue by tianyayouxiaer** [mcollina/aedes#47]
I have see that the heartbeatInterval is for cluster,so can I consider that the aedes will be support cluster mode? and how long time it will come to become reality!
thanks very much!

**Comment by mcollina** [comment]
You can already use this on top of redis or mongo. The cluster module support will come soon.

**Comment by tianyayouxiaer** [comment]
thank you for your reply,does aedes can support  multi-core use it on top of redis now,or when it support the cluster mode ,it will can be support multi-core?

**Comment by mcollina** [comment]
you can run as many processes with aedes running on top of redis, they will communicate between each other via redis.

**Comment by tianyayouxiaer** [comment]
thank  you for your reply,I test the websocket connection from  web just as the mosca does,and I find that it can not work ,does the aedes  not support websocket client now?

**Comment by mcollina** [comment]
aedes runs on top of streams. You need to use websocket-stream
