### ISSUE TITLE
unable to unsubscribe topics after client disconnects

### ISSUE THREAD

**Issue by mohkar** [mcollina/aedes#49]
Hi Mcollina,

I want to unsubscribe to all the topics a client has subscribed to when he disconnects. After I reconnect I should not get messages of those topics unless I subscribe again. In order to achieve this on 'clientDisconnect' and 'clientError' events I am trying to explicitly unsubscribe to  the topics. However, on these events I am getting 'subscriptions' object of the client as empty. But when I connect again, I am getting back all subscriptions on the 'subscriptions' object. 

PS: I am using cleansession: false on client. QOS: 1

**Comment by mcollina** [comment]
Just use `cleansession: true` on the the client, that will do.

What code are you using to achieve this? It _should_ work even if it was not intended to be used that way.

**Comment by mohkar** [comment]
Yes, I am aware of that, but 'cleansession : true' will not hold messages if the client ungracefully disconnects which is something I would not want. 
My main concern was, client object is not containing subscriptions in 'subscriptions' field of client on 'clientDisconnect' event.

**Comment by mcollina** [comment]
Those would already be gone, as with the 'clientDisconnect' event the client has no live subscriptions (that is used for live subscriptions). At the moment, that fied is not part of the public API and it is used internally. 

I am fine in exposing this, but it would require a bit of work around doc and testing. The idea should be to have that flushed if the client is clean, but to maintain the state if the client is not clean.

BTW, to achieve what you want, it might be simpler to hook into the persistence and delete them from there directly.

If you want to send a PR, I will be happy to review.

**Comment by mohkar** [comment]
Hi mcollina,
As you mentioned, I tried deleting subscriptions from redis manually. I did following:
On unsubscribing I deleted client key that is - 'client:sub:{client}' and
removed client entry from subscribed channels - 'sub:client:{subscription}'
However, the aedes is somehow still holding subscriptions and fetching me all the retained messages.

Could you please suggest me how to remove subscriptions completely from aedes.

**Comment by mcollina** [comment]
You must use the persistence api: https://github.com/mcollina/aedes-persistence
In particular, you need to use: https://github.com/mcollina/aedes-persistence#instancecleansubscriptionsclient-callbackerr-client

(all persistences implement the same API).

**Comment by mohkar** [comment]
I tried using instancecleansubscription() method and I was able to completely remove clients subscriptions. 
Thanks.
