### ISSUE TITLE
repeated connects/disconnects...

### ISSUE THREAD

**Issue by bblumberg** [mcollina/aedes#50]
I am using aedes with mqtt.js on 1 machine. I can get aedes into a state where the client connects and then  immediately disconnects. The connection appears to be successful (i.e., i get back a successful connection). It seems to occur when there is either a heavy load on aedes (for example, when I am creating 20 clients all at one time), but can also happen sometimes when in the connect handler, I set up a few subscriptions. In the case when I have 20 clients (all identical), 2 will display this behavior: they will connect, immediately be disconnected, and then repeatedly reconnect and be disconnected.

It is intermittent, and when it doesn't occur I am blown away by the performance of aedes (Very nice job).

I don't see this behavior when using the same code to connect to mosca or mosquitto. 

I have attached the 2 source files that demonstrate this behavior. Any help would be greatly appreciated.

bb
[aedes example.zip](https://github.com/mcollina/aedes/files/258006/aedes.example.zip)

**Comment by mcollina** [comment]
Thanks! Aedes _will_ become the core of Mosca soon, and thanks for trying it out. The current version of Mosca has been battle tested, while this is still new (and a complete rewrite).

I don't have much time to look into this right now, I hope to have some time in the next couple of weeks.
In the meantime, you can try without using redis or level, just because it might be a bug there.

**Comment by bblumberg** [comment]
Totally understand. For what it is worth it seems to be closing the client
because onend() in end-of-stream is being called. When you get to it maybe
that will help.

Thanks for your great work!!!

bb

On Tuesday, May 10, 2016, Matteo Collina <notifications@github.com> wrote:

> Thanks! Aedes *will* become the core of Mosca soon, and thanks for trying
> it out. The current version of Mosca has been battle tested, while this is
> still new (and a complete rewrite).
>
> I don't have much time to look into this right now, I hope to have some
> time in the next couple of weeks.
> In the meantime, you can try without using redis or level, just because it
> might be a bug there.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mcollina/aedes/issues/50#issuecomment-218304157>
>


-- 

*. **.* *.*
* Bruce Blumberg *|  Principal Software Engineer
*Rethink Robotics, Inc *
main: 617.500.2487  | cell: 978.430.2206

**Comment by mcollina** [comment]
There was a problem in your script, as the `clientId` were not really unique, and there were quite a few duplicates.

This is not causing the issue:

```js
/**
 * Created by bblumberg on 3/3/16.
 */
'use strict'
var cluster = require('cluster');
var mqtt    = require('mqtt');
var numProcesses = 30;
var interval = 1;
var id = 0;

if(cluster.isMaster) {
  for(let j = 0; j < numProcesses; ++j){
    cluster.fork();
  }
}
else {
  let i = 0;
  var connect_options = {
    keepalive: 6000,
    clean: true,
    clientId: 'worker-' + process.pid
  };
  var client  = mqtt.connect('mqtt://localhost:1883', connect_options);
  client.on('connect', function (options) {
      client.publish('presence/topic', 'Hello mqtt');
      client.publish('presence/topic', 'Another message');
    }
  )

  client.on('disconnect', function () {
    console.log(client.options.clientId, 'disconnected')
  })

  setInterval(function() {
    client.publish('presence/topic/json', JSON.stringify({
      type: 'bird',
      color: 'green',
      count: i,
      time: new Date
    }, null, ''));
    i++;
  }, Math.ceil(50 * Math.random()))
  client.on('error', function(error) {console.log('error occurred '  + JSON.stringify(error, null, ' '))})
  cluster.on('disconnect', function () {
    console.log('master died exiting')
    process.exit(0)
  })
}
cluster.on('online', function(worker) {
  console.log('Worker ' + worker.process.pid + ' is online');
});
```
