### ISSUE TITLE
More events

### ISSUE THREAD

**Issue by behrad** [mcollina/aedes#55]
In Mosca, I've configured a custom bunyan-stream module to capture `keepalive timeout` & `setting keepalive time` events since these are logged using bunyan.

Can we add two more `emit`s for these in aedes @mcollina ?

**Comment by mcollina** [comment]
yeah, no problem in more emits.

Aedes and mosca v2 will use pino. It's 4-5 time faster than bunyan. I have
a snippet for mosca v1 if you want.
Il giorno ven 17 giu 2016 alle 19:41 Behrad <notifications@github.com> ha
scritto:

**Comment by behrad** [comment]
> Aedes and mosca v2 will use pino. It's 4-5 time faster than bunyan

And this is with high verbose levels? Or even if log level is ERROR?



> I have
> a snippet for mosca v1 if you want

What snippet?

**Comment by mcollina** [comment]
Yes, you can high verbosity without a huge impact on perf: replacing
winston in a normal web app gives 20-50% throughput boost. I'm not at my
laptop, I'll send the snippet for mosca v1 soon.
Il giorno ven 17 giu 2016 alle 19:58 Behrad <notifications@github.com> ha
scritto:
