### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by dottgonzo** [mcollina/aedes#58]
hi @matteo,
is possible to get the ip addess of a client? Or can you suggest me where is convenient to edit aedes or its modules, to add more information about the client (as the ip address) when the server parse the messages coming from mosca or other mqtt clients?

**Comment by mcollina** [comment]
The underlining stream is available at https://github.com/mcollina/aedes/blob/master/lib/client.js#L21.
Refer to the stream (net, ssl, websocket-stream, etc) to how to get that information.

**Comment by mcollina** [comment]
If you want to send a PR to make that easier, please do :).
