### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by laszbalo** [mcollina/aedes#61]
Hi,

I am trying to use aedes with websockets like this:

```javascript
import ws from 'websocket-stream'
const aedes = require('aedes')()
const server = ws.createServer({port: 9001}, aedes.handle)
```

in the browser I implemented a basic client with Paho, that can publish and subscribe to messages from the same topic.

However, when I send MQTT messages to Aedes this is what is coming back from the broker:

After the first message, I got back a 2 bytes long payload: 0 followed by the first character of the original message sent.

After that there is no more incoming messages, regardless of how many times I send a message to the broker.

BTW, the client works great with no modification when I switch to mosquitto with websocket support.

Does my Aedes code look OK to you?

**Comment by mcollina** [comment]
I don't think the code is correct, as you need to pass an instance of httpServer to ws.

**Comment by laszbalo** [comment]
I have tried with passing a reference to a httpServer instance, as you suggested, but still getting the same error. If you could have a quick look at it,  I created a small repo [here](https://github.com/laszbalo/aedes-websockets-paho) .

**Comment by mcollina** [comment]
I've tested your script, and it is received the first message and not the second. I'm not exactly sure what's going on. Can you check with MQTT.js if you have the same behavior?

**Comment by laszbalo** [comment]
I have tried MQTT.js as well and it works with booth Aedes and Mosquitto.
I intend to use mqtt from the browser, therefore I'd try to avoid MQTT.js, because of it's massive file size.

I did a quick comparison by watching the number of frames and frame sizes inside the Chrome's network panel, and found that Mosquitoo sends back only one frame, while Aedes split up the response, and in my case, sends back the result in 5 frames. MQTT.js can handle both cases well, while Paho seems to work only with the single frame case. 
What do you think, is this something to do with Paho or with Aedes?

These are the details of my finding:

message: '**Tally-ho!**'
topic: **World**

MQTT.js - Mosquitoo
18b -> (sent by MQTT.js)
18b <- (sent by Mosquitoo)

MQTT.js - Aedes
18 ->
1<-
1<-
2<-
5<- (topic name; came back as plain text)
9<-

Paho - Mosquitto
18->
18<-

Paho - Aedes
18->
1<-
1<-
2<-
5<- (topic name; came back as plain text)
9<-

**Comment by mcollina** [comment]
According to http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718127, packets can be divided between multiple frames.

**Comment by laszbalo** [comment]
Thank you for your help, in that case I will open a new issue at the Paho's issue tracking page.

**Comment by laszbalo** [comment]
I have got just one more question about control packets and topic name. 

> MQTT Control Packets MUST be sent in WebSocket binary data frames. If any other type of data frame is received the recipient MUST close the Network Connection

Aedes sends back the topic name in plain text. Is the topic name is part of the control packet?

**Comment by mcollina** [comment]
@laszbalo yes.

**Comment by laszbalo** [comment]
In that case, should Aedes not send the topic name in a binary frame instead of a text frame? It seems that Paho does the right thing when it closes the connection upon the arrival of a text frame.

**Comment by mcollina** [comment]
Sorry, the topic name is UTF-8, and it should be part of a MQTT packet sent as binary.

However
https://github.com/maxogden/websocket-stream/blob/master/stream.js#L72

is not specifying that the packet is binary:
https://github.com/websockets/ws#sending-binary-data

Either paho.js is very strict, or there is a bug in websocket-stream.

**Comment by laszbalo** [comment]
To quickly check, I've changed https://github.com/maxogden/websocket-stream/blob/master/stream.js#L62 to 
```javascript
socket.send(chunk, {binary: true}, next)
```
with this modification Paho works fine with Aedes.

**Comment by mcollina** [comment]
Can you please send a PR against websocket-stream, making that configurable?

**Comment by laszbalo** [comment]
Sure, I will give it a go tonight or tomorrow.

**Comment by laszbalo** [comment]
Sorry for the late reply, but life overrode my timetable for the weekend. PR sent.

**Comment by mcollina** [comment]
This was fixed in websocket-stream.
