### ISSUE TITLE
Why are messages with qos 2 stuck on redis when we have that client connected and subscribled?

### ISSUE THREAD

**Issue by guptaashishiitr** [mcollina/aedes#63]
Hi 
We have scenario as below
1. ClientA connects with qos2 and subscribes to /user/testtopic
2. ClientB publishes Message1 and it is delieverd fine
3. ClientA turns off internet
4. ClientB publishes Message2,Message3 etc 
5. ClientA turns internet on
6. Client ONLY GETS ONE MESSAGE and rest all are stuck in redis

If client A turns off internet again and turns it on again it gets couple of messages again
Why are "all" not delivered on time and in sequence?

UPDATE - It sends in chunks of 4 actually. So, if client A turns internet off and turns it back on it receoves another set of pending 4.  Why is the order not maintained?

Clean session property is false and retain is also false and qos is 2

Thanks,
Ashish

**Comment by mcollina** [comment]
Can you please upload a client & server to reproduce? Ideally in Node.js.

**Comment by guptaashishiitr** [comment]
> Broker file as below and logger file just generates logs to check if there are any errors. I have removed publish auth and sub scribe auth/connect auth from the file. Client you can pretty much use any (even any browser based or light weight client will do) Settings for client are
1. QOS 2
2. Clean : true
3. KeepAlive - 300
(We have connect auth also but you can skip that)
Steps 
1. Subscrible client 1 to a topic (Redis will show cached subscriptions and client)
2. Disconnect and connect client 2 (Redis will show cached subscriptions and client)
3. Publish to topic client 1 has above about 10 mesages with qos 2 / retained as false
4. Disconnect and connect back as client 1 and subscrible to topic

If you want exact files and tests let me know, I can write quick node project.


`// MQTT Broker Setup
var logger = require('./config/logger');
var common = require('./config/common');
var config  = common.config()

function aedesConnect() {

    var models = mongoose.models

    var redispersistence = require('aedes-persistence-redis')({
        host: config.REDIS_CONNECTIONURL,
        port: config.REDIS_PORT,
        password: config.REDIS_PASSWORD
    });


    var aedes = require('aedes')({
        persistence: redispersistence,
        connectTimeout: config.MQTT_CONNECTTIMEOUT
    });

    var aedesServer = require('net').createServer(aedes.handle)

    var settings = {
        port: config.MQTT_PORT,
    };

    // Authentication method
    aedes.authenticate = function (client, username, password, callback) {
        var authorized = true
	callback(null, authorized);
    }

    // Authorize Publish Method
    aedes.authorizePublish = function (client, packet, callback) {
	return callback(null)
    }

    ////Authorize Subscribe Method
    aedes.authorizeSubscribe = function (client, sub, callback) {
        callback(null, sub)
    }


    var port = 1883

    aedesServer.listen(port, function () {
        logger.info('mqtt broker listening on port ' + port)
    })


    aedes.on('clientError', function (client, err) {
        logger.error(err)
        logger.error('client error', client.id, err.message)
    })

    aedes.on('clientDisconnect', function (client) {
        logger.info('Client disconnected - ', client.id)
    })

    aedes.on('unsubscribe', function (unsubscriptions, client) {
        logger.info('Client unsubscribed - ', client.id, unsubscriptions.toString())
    })

    aedes.on('publish', function (packet, client) {
        if (client) {
            logger.info('message published from client', client.id, " to ", packet.topic, packet.messageId)
        }
        else {
            logger.info('message published from broker to ', packet.topic, packet.messageId)
        }
    })

    aedes.on('client', function (client) {
        logger.info('new client', client.id)
    })

    return aedes;
}

module.exports = aedesConnect
`

**Comment by mcollina** [comment]
I cannot reproduce, things works smoothly here. Please upload a test client that makes the server exhibit the bug.

I am publishing a QoS 2 message with `retain:false` using MQTT.js.

Which version of Redis are you using? I'm testing on 3.2.0.

**Comment by guptaashishiitr** [comment]
I am using redis version 3.0.3
I will replicate it with MQTT.js and paste details here

**Comment by guptaashishiitr** [comment]
@mcollina  We were facing a lot of issues and have switched to mosquitto and we have had no problems since then. I definitely want to contribute to this amazing project and will add sample client files to replicate the issues but to summarize issue is -

QOS2 offline messages are not delivered in order and all of them are not delivered but in chunks of 4 or less. So if I sent 10 messages when client 2 is disconnected, whenever it conencts back it wont get all 10 and also in random order. 

Will add sample client files and broker files in couple of days as we are having a release tomorrow.
Thank you for all the help.

**Comment by mcollina** [comment]
I've done another round of testing, confirmed odd behavior both with redis and without.

Thanks for reporting, I'll look into it as soon as possible (it might take a while).

**Comment by igormontella** [comment]
Hello @mcollina, could you describe the error, I'm facing the same problem, the clients are receiving the same message multiple times.
If could you describe it a bit, I could help and make a PR.

Thanks!

**Comment by mcollina** [comment]
@igormontella thanks! Really, I have just tested the above code. This needs to be triaged and debugged, feel free to dig into it and report with any questions, it will make solving this much quicker.

**Comment by GavinDmello** [comment]
@guptaashishiitr @igormontella We made some change in aedes-persistence redis. Could you guys check if you're still facing this issue ?

**Comment by rasalasantosh** [comment]
@GavinDmello , Offline messages are not delivered in order ,tested with both QoS1 and Qos2 .

**Comment by GavinDmello** [comment]
@rasalasantosh  Are you getting all of them though ?

**Comment by rasalasantosh** [comment]
@GavinDmello ,yes all are delivered.

**Comment by GavinDmello** [comment]
@rasalasantosh  Got it @mcollina I think scan returns data in random order

**Comment by mcollina** [comment]
I'm starting to think that using SCAN was not a good idea in the first place. Maybe we should go for the same approach of Mosca.

**Comment by GavinDmello** [comment]
I think this should be solved in the latest version of redis persistence redis
