### ISSUE TITLE
about subscribed clients list

### ISSUE THREAD

**Issue by sfsw** [mcollina/aedes#64]
hi, is that any way to check how many client subscribed a topic?

**Comment by GavinDmello** [comment]
Hi, If you're using aedes with redis-persistence then you can get the the list of clientIds against a hash key which looks like `sub:client:topic`

**Comment by mcollina** [comment]
It would be a nice PR for aedes-persistence.

**Comment by sfsw** [comment]
thanks GavinDmello, i found that `aedes.clients` saved all clients info.

this code is what i want:
`aedes.clients[Object.keys(aedes.clients)].subscriptions`

is that ok ?

**Comment by GavinDmello** [comment]
This approach will work if you have one client subscribing, may not work for multiple clients.

**Comment by sfsw** [comment]
@GavinDmello yeah! thanks for help
