### ISSUE TITLE
Inflight messages / QoS 1 support for instance.publish()

### ISSUE THREAD

**Issue by yentsun** [mcollina/aedes#67]
Hi, Matteo!

I appreciate your work very much since Mosca, and having an embedded broker with custom auth is awesome!

I'm having some issues with achieving QoS 1 behavior when publishing from the broker (not from a client) though. I've set up `aedes-redis-persistence` and retained messages work fine:

     instance.publish({topic: 'cloud/update', payload: buffer, retain: true})

 and I can see them in Redis. But if I try to 

    instance.publish({topic: 'cloud/update', payload: buffer, qos: 1})

 instead - I don't see any inflight messages while no clients connected.

I actually switched to Aedes from Mosca in hope to achieve this, but still no luck. Retain also worked in Mosca but no inflight messages for QoS 1 stored. Maybe I'm doing something wrong?

**Comment by mcollina** [comment]
You need to subscribe your clients with clean:false.

**Comment by yentsun** [comment]
@mcollina thanks for the quick response! I guess I'm doing it already (I'm using the mqtt-spy client). Ok, I will conduct more tests with different clients.

**Comment by yentsun** [comment]
the first test with mqtt.js:

```
var mqtt = require('mqtt');
var client  = mqtt.connect('mqtt://localhost', {clean: false, clientId: 'hkkm65'});

client.on('connect', function () {
    client.subscribe('cloud/5rbo2n/update', {qos: 1}, function(error, granted) {
        console.log(error, granted);
    });
});

client.on('message', function (topic, message) {
    // message is Buffer
    console.log(message.toString());
    client.end()
});
```

...proved the outgoing messages do work, could see them in Redis too.

As for anybody using mqtt-spy, `Clean session` checkbox doesn't seem to work:

![selection_051](https://cloud.githubusercontent.com/assets/630971/18747466/b9ddb21e-80f7-11e6-9e51-7773951dc8ed.png)

Thanks, Matteo! Sorry to bother with this.

**Comment by mcollina** [comment]
No problem @yentsun!
