### ISSUE TITLE
client parameter is null on publish event

### ISSUE THREAD

**Issue by jeremytregunna** [mcollina/aedes#7]
Like the title says, when implementing the publish event like this:

```js
aedes.on('publish', function(packet, client) {
  console.log('client = ' + client);
});
```

The console will always be `null`. The little documentation that's in place tends to lean towards that `client` should be populated except for internal messages. Is this a wrong assertion? If so, in what cases should the publish event return a client?

**Comment by mcollina** [comment]
That should be the case, `client` will be populated when there is a client.
If not, that would be a bug.

How do you reproduce?

**Comment by jeremytregunna** [comment]
So I'm using mosquitto_pub/sub to test. The `client` event shows the client, but when I run:

`mosquitto_pub -t test -m 123`

And in the server code I'm using the above posted code, I always see `client = null` in my console.

**Comment by mcollina** [comment]
Releases as 0.10.3.
