### ISSUE TITLE
Publishing 2048 bytes messages at a high rate, they are lost at all QOS

### ISSUE THREAD

**Issue by cordovapolymer** [mcollina/aedes#74]
I'm trying to switch to aedes from mosquitto.
Using your example.js.
I'm publishing 667 2048bytes messages with QOS 2,1 or 0 at a high rate. I publish via mqtt, and receive both via mqtt and websocket, all messages are lost.
This warning is show in the output several times in between of 'message from client' messages.
`Warning: Possible EventEmitter memory leak detected. 201 drain listeners added. Use emitter.setMaxListeners() to increase limit`
I tried to send the same data in 256bytes messages, and they were lost as well.
Then I've tried to send 20480bytes messages and as soon as there were only 67 in total, they were delivered. 204800bytes messages are delivered as well.

**Comment by rahulbhanushali** [comment]
With a minor tweak to EventEmitter settings, this can be avoided.  More on this [here](https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n).

To solve the issue you could add this line to your index file:

`process.setMaxListeners(0) `

If that doesn't solve the problem, you could also add this line in the `connackSent` event handler:

`client.conn._maxListeners = 500;`

**Comment by GavinDmello** [comment]
@cordovapolymer  You can try bumping the `concurrency` param in the Aedes options to a sufficient amount to avoid the warning, but in which ways messages shouldn't be dropped.

**Comment by mcollina** [comment]
can you please a testing script so we can easily reproduce?

**Comment by cordovapolymer** [comment]
@rahulbhanushali tryed process.setMaxListeners(0), seems that the warning was suppressed, but messages are still not delivered.
@GavinDmello tried setting concurrency param to 1000 and 10000, nothing changed.
@mcollina 
> can you please a testing script so we can easily reproduce?
`// mqtt.js
/*jslint node: true, esversion: 6 */
'use strict';
console.log("loading mqtt-test module");

module.exports = class Mqtt {
    constructor() {
      console.log("instanciating mqtt module");
      this.mqtt = require('mqtt');
      this.client  = this.mqtt.connect('mqtt://broker');
      var data;
      data.message = 'your large message';
      data.topic = 'message/topic';
      var jsonMessage = JSON.stringify(data.message);
      if(jsonMessage.length >= 20480){
        var messageChunks = this.chunkSubstr(jsonMessage, 20480);
        var messageId = Math.random().toString(36).substr(2, 16);
        var chunkNumber = 0;
        var totalChunks = messageChunks.length;
        messageChunks.forEach(function(messageChunk) {
          var chunk = {data: {}};
          chunk.partial = {};
          chunk.partial.number = chunkNumber;
          chunk.partial.id = messageId;
          chunk.partial.total = totalChunks;
          chunk.data = messageChunk;
          chunk.topic = jsonMessage.topic;
          this.client.publish(data.topic, JSON.stringify(chunk), {'qos': 2});
          chunkNumber++;
        }, this);
      }
      else{
        this.client.publish(data.topic, jsonMessage, {'qos': 2});
      }

      this.client.on('connect', function () {
        console.log("MQTT connected");
      }.bind(this));
      console.log("finished instanciating mqtt module");
    }

    chunkSubstr(str, size) {
      var numChunks = Math.ceil(str.length / size),
          chunks = new Array(numChunks);

      for(var i = 0, o = 0; i < numChunks; ++i, o += size) {
        chunks[i] = str.substr(o, size);
      }

      return chunks;
    }
};

console.log("loaded mqtt-test module");
`

**Comment by GavinDmello** [comment]
@cordovapolymer I wasn't able to detect any problem at my end.  Is the receiver is offline when these messages are published ? If so, try using clean false. Also it would be a good idea to defer your publishes to on connect-`Just a suggestion`.

**Comment by mcollina** [comment]
@cordovapolymer it seems your code is supposed to be used required by some other module? Can you make it so that we can just run it?

It would be easier to reproduce the problem.

**Comment by cordovapolymer** [comment]
@mcollina , I've updated the code to run standalone. Narrowing the problem- as I've found out 2773 messages are successfully received via mqtt protocol, but are not via websocket. 
I'm using standart [mqtt.js](https://github.com/mqttjs/MQTT.js) client. 
When changing maximum message length in ` if(jsonMessage.length >= 2048){
        var messageChunks = this.chunkSubstr(jsonMessage, 2048);` to 204800 bytes 28 messages are successfully received both via mqtt and websocket.

**Comment by mcollina** [comment]
On my tests, I am getting exactly 2773 messages over ws. Can you please a full project that exhibit this issue? Is this happening on the browser?

**Comment by cordovapolymer** [comment]
@mcollina 
I will publish it a bit later because I'll have to prepare it, last week I've been trying to solve another issue which I'm going to publish right now.

**Comment by mcollina** [comment]
Ping, any update on the example to replicate?
