### ISSUE TITLE
Cluster support

### ISSUE THREAD

**Issue by igormontella** [mcollina/aedes#76]
There is a roadmap or a due date for the cluster support become available? Is there any simple alternative that I could implement to solve this point?

**Comment by mcollina** [comment]
So, it just needs some testing. It should already be possible with the combination of:

https://github.com/mcollina/mqemitter-child-process
https://github.com/mcollina/aedes-persistence-level
https://www.npmjs.com/package/level-party

There might be bugs, and I have never tried it.

Please open bugs if you find them.

**Comment by igormontella** [comment]
Do you recommend any tests? I'm a bit lost in what kind of test I should do.

**Comment by mcollina** [comment]
Write a file where you use all three, and check if it works with cluster.
Put it on a gist, so I can easily check what's going on, and help if needed.

**Comment by behrad** [comment]
1) Can https://github.com/mcollina/mqemitter-child-process be used with redis-persistence?

2) it seems https://github.com/mcollina/mqemitter-child-process only scales-up, what about scaling out (clustering against different machines)?

**Comment by mcollina** [comment]
1. yes.
2. currently not. Performance-wise, you are much better in using redis for everything if you are on multiple machines. However, you can send a PR and make this configurable https://github.com/mcollina/mqemitter-child-process/blob/master/index.js#L43.

**Comment by behrad** [comment]
child-process seems to share an extra process containing actual subscription trie (which may be huge in production) between local processes of broker. This should improve startup time and memory efficiency if so!

> you are much better in using redis for everything if you are on multiple machines.
what about extending `aedes-persistence-redis` to support redis cluster for sharded subscriptions? this seems another approach... Any plans on your side for this?

**Comment by mcollina** [comment]
@behrad yes you are right.

**Comment by behrad** [comment]
> you are much better in using redis for everything if you are on multiple machines.

what about extending `aedes-persistence-redis` to support redis cluster for sharded subscriptions? this seems another approach... Any plans on your side for this?

**Comment by mcollina** [comment]
what do you mean sharded subscriptions?

**Comment by behrad** [comment]
instead of keeping a whole trie in a single redis instance and a clone of that inside each broker node memory, we shard them inside a cluster of redis instances. Each broker node will manage it's own shard of trie...  nodes will use redis pub/sub for inter-node publishes across the whole logical trie... broker nodes should be multi master.

**Comment by mcollina** [comment]
that is implemented on https://github.com/mcollina/upring-pubsub. No need for Redis.

**Comment by behrad** [comment]
Interesting module @mcollina 
Can you elaborate more on this? never heart of word `upring`.
Is this playing the role of a backend only? what about persistence?

**Comment by mcollina** [comment]
the moment I get time to do it, we will have it also for persistence.
It's based on a consistent hashring and the dynamo paper http://s3.amazonaws.com/AllThingsDistributed/sosp/amazon-dynamo-sosp2007.pdf.

**Comment by wuhkuh** [comment]
I deem it wise to make a separate branch for this, as clustering the aedes could have some complications like race conditions, until the very moment it is deemed stable enough to be pushed to master. This way we can implement some tests for the cluster module as well.

But this is of course from a sideline perspective, I don't know how far @mcollina already is in the development process.

**Comment by mcollina** [comment]
Aedes does not need a separate branch.
All needs to be handled in the packages that I mentioned before.
Feel free to wrap everything in an easy-to-use fashion, and do the testing there.

**Comment by igormontella** [comment]
I've used aedes-persistence-redis, mqemitter-redis and HAProxy, works fine.
