### ISSUE TITLE
no such packet Error: no such packet

### ISSUE THREAD

**Issue by battuashwik** [mcollina/aedes#83]
Sending message via client.publish with qos 2 and retain false. Client connects with cleanSession true. Also using in memory store.

**Comment by mcollina** [comment]
@battuashwik can you please upload a full example to reproduce?

**Comment by battuashwik** [comment]
`var aedes = require('aedes')()
var server = require('net').createServer(aedes.handle)
var port = 1883;
function getRandomInt(min, max) {
  min = Math.ceil(min);
  max = Math.floor(max);
  return Math.floor(Math.random() * (max - min)) + min;
}


aedes.on('clientError', function (client, err) {
  console.log('client error', client.id, err.message, err.stack)
})

aedes.on('publish', function (packet, client) {
  if (client) {
    console.log('message from client', client.id)
  }
})

aedes.on('client', function (client) {
  console.log('new client', client.id)
  	if (client.id === 'device11') {
	  setInterval(function() {
	  	client.publish({
			cmd: 'publish',
			messageId: getRandomInt(0, 10000),
			qos: 2,
			dup: false,
			topic: 'test',
			retain: false
		}, function() {

		});
	  }, 5000);
	}
});

server.listen(port, function () {
  console.log('server listening on port', port)
});


`

**Comment by battuashwik** [comment]
This is the complete example. @mcollina Can u please help with this, its the only thing blocking to use aedes for me, need to integrate asap.

**Comment by mcollina** [comment]
@battuashwik I currently have no time to try a fix, would you like to send a pull request? let me know if you have any questions.

**Comment by battuashwik** [comment]
Can u guide me about the fix, I am more than happy to raise a pull request.

**Comment by GavinDmello** [comment]
@battuashwik @mcollina  I think the issue is clean true. Outgoing enqueue is missed and  doesn't find the client in the outgoing object during `outgoing-update` , Here `https://github.com/mcollina/aedes-persistence/blob/master/persistence.js#L187`. We could just forward packets with clean true

```
  if (client.clean) {
     return cb(null, client, packet)
  }
```
I think this should fix it

**Comment by battuashwik** [comment]
@GavinDmello  Hey, yep just realised that, went through the source. Thanks a lot.

**Comment by mcollina** [comment]
It seems this line is never tested: https://coveralls.io/builds/9871412/source?filename=lib%2Fclient.js#L167.

I would start writing a failing unit test, and adding it to https://github.com/mcollina/aedes/blob/master/test/client-pub-sub.js or https://github.com/mcollina/aedes/blob/master/test/qos2.js.

I think this https://github.com/mcollina/aedes/blob/master/lib/client.js#L157 is wrong, and we should always enqueue.

**Comment by cordovapolymer** [comment]
this is a great fix, aedes is much more stable now.
How can such error be fixed for a situation when a client has published a message and server has been restarted that moment, so server doesn't know about the packet, and a client still waits for it?
