### ISSUE TITLE
Subscription breaks broker events

### ISSUE THREAD

**Issue by wuhkuh** [mcollina/aedes#90]
**Problem:**
Aedes publish events break on client subscription

**Reproduction:**
- Use the testing suite from #88, and add the line
`aedes.on('publish', (x) => console.log('EVENT: publish', x.payload.toString()))`
to the aedesbroker.js file.
- Start the broker.
- Connect as many publishing clients (client2.js) as you want.
- Check the broker console and view the output: loads of packets coming through.
- Connect a subscribing client (client1.js).
- Check the broker console, find out there are no more packets coming through and therefore no events being emitted.

**Comment by cordovapolymer** [comment]
Very interesting, I have seen this behavior on client reconnection, I described it in https://github.com/mcollina/aedes/issues/77

**Comment by GavinDmello** [comment]
The issue in fast-parallel where the final callback does not get called after calling the deliver Qos functions.

**Comment by GavinDmello** [comment]
@mcollina I think <a>https://github.com/mcollina/aedes/blob/master/lib/client.js#L86</a> this callback should be called no matter what the result of toForward is. 
This is called the final callback which will emit the publish event

**Comment by mcollina** [comment]
This should be fixed in #91
