### ISSUE TITLE
client._keepaliveInterval is -1 after connection

### ISSUE THREAD

**Issue by anani112** [mcollina/aedes#99]
I have an embedded client setup with a keepalive timeout of 120 seconds. I have confirmed that the client sends a ping packet every 60 seconds. However, my broker throws a "keep alive timeout" error 180 seconds after connection. I edited the library to keep track of the client._keepaliveInterval variable and it turns out that even though it is correctly setup in https://github.com/mcollina/aedes/blob/9771fd7967112c28e9670b6df04cce38b1e59d59/lib/handlers/connect.js#L41

its value reverts to -1 when I read it using the following code:
```javascript
aedes.on('client', function (client) {
    console.log("Keepalive timeout: " + client._keepaliveInterval);
  connectionController.onConnect(client);
})
```

Any suggestion on how to handle this issue?

**Comment by mcollina** [comment]
can you send a PR with a broken unit test to reproduce?

**Comment by anani112** [comment]
I tried replicating the issue with the mqtt.js client but couldn't. It's probably an issue with my embedded mqtt client library. https://github.com/mcollina/aedes/blob/9771fd7967112c28e9670b6df04cce38b1e59d59/lib/client.js#L119 this line gets called multiple times even after successful connection and that's why the first keep-alive timer doesn't get rescheduled when a ping or any other packet is received.

**Comment by mcollina** [comment]
it's hard for me to fix without a way to replicate. You might want to try with http://npm.im/mqtt-connection, which allows you to send individual MQTT packets, and maybe to reproduce the issue.

Mosca is way more battle-tested than Aedes.

**Comment by GavinDmello** [comment]
@mcollina This is amazing. I get something similar in busboy.

**Comment by GavinDmello** [comment]
@anani112 Just a bit curious. Does your client send `pingreqs` ?
You might have find something checking the packets you get mqtt.js (if it works) and checking what packets you don't get on your client.

**Comment by mcollina** [comment]
Any updates on this?

**Comment by anani112** [comment]
Hey sorry for the delay. I think i found out what's causing the issue I was facing. In my setup I have a load balancer in front of my broker instance (using AWS ELB) but I also need access to the original client IP address instead of the load balancer. So to parse the original client IP address from the incoming TCP connections I use this library: https://github.com/findhit/proxywrap and setup my MQTT broker the following way: 
```
var aedes = require('aedes')(aedesOptions);
var rootNet = require('net');
var proxiedNet = require('findhit-proxywrap').proxy(rootNet, {strict: false} );
var server = proxiedNet.createServer(aedes.handle);
```

When set up that way my clients loose connections regardless of my MQTT timeout value or load balancer timeout parameter. The weird thing is that this only happens when I'm actually in the cloud (ie: not on my local machine where I connect directly to the broker instead of the ELB load balancer - the proxywrap library lets you receive both standard TCP connections or TCP connections using the Proxy protocol). The connection/timeout issue goes away when I setup my broker without the proxywrap. 
I still don't know exactly why that's happening (beyond my expertise) but I will look for other ways to get the client IP address. suggestions are welcome :)

**Comment by mcollina** [comment]
I think there might be a bug in `findhit-proxywrap`, or some bad interaction with the two modules.
I have not many suggestions on this one :(. You might try a debug session on the cloud, and see what causes the timeout to go negative.
